You are going to let the fear of poverty govern your life and your reward will be that you will eat, but you will not live. -- George Bernard Shaw

diff --git a/03228e9c4c35460cb75a0d6d43edcaa0 b/03228e9c4c35460cb75a0d6d43edcaa0
--- a/03228e9c4c35460cb75a0d6d43edcaa0
+++ b/03228e9c4c35460cb75a0d6d43edcaa0
@@ -1,48 +1,51 @@
-2017年 10月 22日 日曜日 10:30:46 JST
-#!/usr/bin/env python3
-# -*- coding: utf-8 -*-
-import numpy as np
-import cv2
+2017年 12月  2日 土曜日 11:01:52 JST
+#!/bin/sh
+#
+# An example hook script to verify what is about to be committed.
+# Called by "git commit" with no arguments.  The hook should
+# exit with non-zero status after issuing an appropriate message if
+# it wants to stop the commit.
+#
+# To enable this hook, rename this file to "pre-commit".
 
-drawing = False
-mode = True
-ix,iy = -1,-1
+if git rev-parse --verify HEAD >/dev/null 2>&1
+then
+	against=HEAD
+else
+	# Initial commit: diff against an empty tree object
+	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
+fi
 
-def draw_circle(event,x,y,flags,param):
-    global ix,iy,drawing,mode
-    if event == cv2.EVENT_LBUTTONDOWN:
-        print ('Push')
-        drawing = True
-        ix,iy = x,y
+# If you want to allow non-ascii filenames set this variable to true.
+allownonascii=$(git config hooks.allownonascii)
 
-    elif event == cv2.EVENT_MOUSEMOVE:
-        if drawing == True:
-            print ('Drawing...')
-            if mode == True:
-                pass
-            else:
-                cv2.circle(img,(x,y),5,(0,0,255),-1)
-        else:
-            pass
-    elif event == cv2.EVENT_LBUTTONUP:
-        print ('Up')
-        drawing = False
-        if mode == True:
-            cv2.rectangle(img,(ix,iy),(x,y),(0,255,0),2)
-        else:
-            cv2.circle(img,(x,y),5,(0,0,255),-1)
+# Redirect output to stderr.
+exec 1>&2
 
-if '__main__' == __name__ :
-    img = np.zeros((512,512,3), np.uint8)
-    cv2.namedWindow('image')
-    cv2.setMouseCallback('image',draw_circle)
-    
-    while(1):
-        cv2.imshow('image',img)
-        k = cv2.waitKey(1) & 0xFF
-        if k == ord('m'):
-            mode = not mode
-        elif k == 27:
-            break
+# Cross platform projects tend to avoid non-ascii filenames; prevent
+# them from being added to the repository. We exploit the fact that the
+# printable range starts at the space character and ends with tilde.
+if [ "$allownonascii" != "true" ] &&
+	# Note that the use of brackets around a tr range is ok here, (it's
+	# even required, for portability to Solaris 10's /usr/bin/tr), since
+	# the square bracket bytes happen to fall in the designated range.
+	test $(git diff --cached --name-only --diff-filter=A -z $against |
+	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
+then
+	echo "Error: Attempt to add a non-ascii file name."
+	echo
+	echo "This can cause problems if you want to work"
+	echo "with people on other platforms."
+	echo
+	echo "To be portable it is advisable to rename the file ..."
+	echo
+	echo "If you know what you are doing you can disable this"
+	echo "check using:"
+	echo
+	echo "  git config hooks.allownonascii true"
+	echo
+	exit 1
+fi
 
-    cv2.destroyAllWindows()
+# If there are whitespace errors, print the offending file names and fail.
+exec git diff-index --check --cached $against --
