You'll never find a rainbow if you're looking down. -- Charlie Chaplin

diff --git a/2c3e8556dc354bb5a2a9effc24fb4e66 b/2c3e8556dc354bb5a2a9effc24fb4e66
--- a/2c3e8556dc354bb5a2a9effc24fb4e66
+++ b/2c3e8556dc354bb5a2a9effc24fb4e66
@@ -1,102 +1,170 @@
-2018年  7月  8日 日曜日 09:54:32 JST
-100
--2.746715e-01	4.191831e-01
--2.931587e-01	2.247797e-01
-2.321991e-01	4.064824e-01
--1.520429e-01	3.578809e-01
--8.481506e-02	-3.058323e-01
-1.856104e-01	2.437552e-02
--3.403643e-01	4.547575e-01
--3.730157e-01	-4.956605e-01
--1.173085e-01	-2.492071e-01
-1.552879e-01	3.449078e-02
-1.099664e-01	-2.121421e-01
-4.092620e-01	2.361288e-01
--3.788992e-01	1.148062e-01
--2.340848e-01	4.453564e-01
--7.531051e-02	-2.516460e-01
-1.772955e-01	-4.287967e-01
--4.426001e-02	-3.237644e-04
--4.797312e-01	3.861750e-01
-1.545830e-01	5.970007e-02
-4.850480e-01	-1.605443e-01
--4.632017e-01	-2.009751e-01
-4.881687e-01	-5.634217e-02
--3.708808e-01	4.150378e-01
--1.135756e-01	-4.695678e-01
--3.155564e-01	4.356883e-01
--1.920876e-02	9.783734e-02
--6.385236e-02	-3.949834e-01
-2.275205e-01	-3.768423e-01
-1.721155e-01	-4.660092e-01
-4.644338e-01	-4.804784e-01
--4.553355e-01	-7.876486e-02
-2.642185e-01	4.444889e-01
-5.434882e-02	1.171663e-01
-1.465040e-01	-1.143288e-01
-4.021194e-01	-1.771178e-01
--7.684997e-02	-4.504972e-02
-7.223762e-02	-4.515364e-01
--2.392842e-02	-3.878574e-01
-3.425949e-01	-1.136164e-01
--4.632521e-01	2.447992e-01
-2.661087e-03	-2.676771e-01
--2.328564e-01	-3.223420e-01
--4.466751e-01	-1.286633e-01
--4.479510e-01	-6.189542e-02
--4.433532e-01	1.711145e-01
--2.251056e-01	-4.814771e-01
-1.644014e-01	3.307433e-01
--4.618902e-01	1.489123e-01
-7.775744e-02	3.332788e-01
-3.334003e-01	-1.894713e-01
--2.498460e-01	-4.304763e-01
--2.016626e-01	-3.888901e-01
-3.431431e-01	-6.968799e-02
-9.800158e-02	3.226420e-01
-1.605654e-01	-8.747274e-02
--4.682621e-01	-3.876081e-01
-2.279104e-01	1.228907e-01
-2.623244e-02	-7.350670e-02
--3.627764e-01	1.817259e-01
-2.810276e-01	4.027677e-01
--1.422834e-01	3.805313e-01
-4.783312e-01	2.763473e-01
--3.893109e-01	2.006641e-03
-3.557465e-01	-1.806598e-01
-1.450046e-01	-2.954686e-01
--2.783369e-01	-3.638557e-01
--7.520648e-02	5.595485e-02
-2.496197e-02	-2.837536e-02
-2.810538e-01	1.905431e-01
--3.170416e-01	-1.766273e-01
-4.882654e-01	-3.097528e-01
--4.631571e-01	-3.453426e-02
--1.609725e-01	4.549768e-01
-8.088132e-03	2.639415e-01
--4.847877e-01	3.397484e-01
-4.413317e-01	-1.913503e-01
--3.675422e-01	2.785392e-01
-3.611714e-01	-2.921098e-01
--4.166281e-01	8.013365e-02
-2.673365e-01	-1.624028e-01
-3.691146e-01	-6.944182e-02
-4.231276e-01	2.426829e-01
--2.873224e-01	2.458353e-01
-3.373099e-01	2.320625e-01
-4.419646e-01	2.934974e-02
-2.343567e-01	-1.409978e-01
--4.534335e-01	4.573376e-01
-3.897785e-01	4.435523e-01
--9.306764e-02	4.667342e-01
-3.670526e-01	-2.663117e-02
--4.954102e-01	-4.096787e-01
--2.756701e-01	-3.467814e-01
--1.885635e-01	-1.210909e-01
--9.027580e-02	-7.420788e-03
-4.672701e-01	1.888859e-01
--2.162385e-01	-3.037337e-01
--4.418227e-01	3.812396e-01
-3.998173e-01	2.168659e-01
-1.527816e-01	-4.239467e-01
-4.445392e-01	2.424582e-01
+2018年  7月 14日 土曜日 11:24:35 JST
+#!/bin/sh
+#
+# Copyright (c) 2006, 2008 Junio C Hamano
+#
+# The "pre-rebase" hook is run just before "git rebase" starts doing
+# its job, and can prevent the command from running by exiting with
+# non-zero status.
+#
+# The hook is called with the following parameters:
+#
+# $1 -- the upstream the series was forked from.
+# $2 -- the branch being rebased (or empty when rebasing the current branch).
+#
+# This sample shows how to prevent topic branches that are already
+# merged to 'next' branch from getting rebased, because allowing it
+# would result in rebasing already published history.
+
+publish=next
+basebranch="$1"
+if test "$#" = 2
+then
+	topic="refs/heads/$2"
+else
+	topic=`git symbolic-ref HEAD` ||
+	exit 0 ;# we do not interrupt rebasing detached HEAD
+fi
+
+case "$topic" in
+refs/heads/??/*)
+	;;
+*)
+	exit 0 ;# we do not interrupt others.
+	;;
+esac
+
+# Now we are dealing with a topic branch being rebased
+# on top of master.  Is it OK to rebase it?
+
+# Does the topic really exist?
+git show-ref -q "$topic" || {
+	echo >&2 "No such branch $topic"
+	exit 1
+}
+
+# Is topic fully merged to master?
+not_in_master=`git rev-list --pretty=oneline ^master "$topic"`
+if test -z "$not_in_master"
+then
+	echo >&2 "$topic is fully merged to master; better remove it."
+	exit 1 ;# we could allow it, but there is no point.
+fi
+
+# Is topic ever merged to next?  If so you should not be rebasing it.
+only_next_1=`git rev-list ^master "^$topic" ${publish} | sort`
+only_next_2=`git rev-list ^master           ${publish} | sort`
+if test "$only_next_1" = "$only_next_2"
+then
+	not_in_topic=`git rev-list "^$topic" master`
+	if test -z "$not_in_topic"
+	then
+		echo >&2 "$topic is already up-to-date with master"
+		exit 1 ;# we could allow it, but there is no point.
+	else
+		exit 0
+	fi
+else
+	not_in_next=`git rev-list --pretty=oneline ^${publish} "$topic"`
+	/usr/bin/perl -e '
+		my $topic = $ARGV[0];
+		my $msg = "* $topic has commits already merged to public branch:\n";
+		my (%not_in_next) = map {
+			/^([0-9a-f]+) /;
+			($1 => 1);
+		} split(/\n/, $ARGV[1]);
+		for my $elem (map {
+				/^([0-9a-f]+) (.*)$/;
+				[$1 => $2];
+			} split(/\n/, $ARGV[2])) {
+			if (!exists $not_in_next{$elem->[0]}) {
+				if ($msg) {
+					print STDERR $msg;
+					undef $msg;
+				}
+				print STDERR " $elem->[1]\n";
+			}
+		}
+	' "$topic" "$not_in_next" "$not_in_master"
+	exit 1
+fi
+
+exit 0
+
+################################################################
+
+This sample hook safeguards topic branches that have been
+published from being rewound.
+
+The workflow assumed here is:
+
+ * Once a topic branch forks from "master", "master" is never
+   merged into it again (either directly or indirectly).
+
+ * Once a topic branch is fully cooked and merged into "master",
+   it is deleted.  If you need to build on top of it to correct
+   earlier mistakes, a new topic branch is created by forking at
+   the tip of the "master".  This is not strictly necessary, but
+   it makes it easier to keep your history simple.
+
+ * Whenever you need to test or publish your changes to topic
+   branches, merge them into "next" branch.
+
+The script, being an example, hardcodes the publish branch name
+to be "next", but it is trivial to make it configurable via
+$GIT_DIR/config mechanism.
+
+With this workflow, you would want to know:
+
+(1) ... if a topic branch has ever been merged to "next".  Young
+    topic branches can have stupid mistakes you would rather
+    clean up before publishing, and things that have not been
+    merged into other branches can be easily rebased without
+    affecting other people.  But once it is published, you would
+    not want to rewind it.
+
+(2) ... if a topic branch has been fully merged to "master".
+    Then you can delete it.  More importantly, you should not
+    build on top of it -- other people may already want to
+    change things related to the topic as patches against your
+    "master", so if you need further changes, it is better to
+    fork the topic (perhaps with the same name) afresh from the
+    tip of "master".
+
+Let's look at this example:
+
+		   o---o---o---o---o---o---o---o---o---o "next"
+		  /       /           /           /
+		 /   a---a---b A     /           /
+		/   /               /           /
+	       /   /   c---c---c---c B         /
+	      /   /   /             \         /
+	     /   /   /   b---b C     \       /
+	    /   /   /   /             \     /
+    ---o---o---o---o---o---o---o---o---o---o---o "master"
+
+
+A, B and C are topic branches.
+
+ * A has one fix since it was merged up to "next".
+
+ * B has finished.  It has been fully merged up to "master" and "next",
+   and is ready to be deleted.
+
+ * C has not merged to "next" at all.
+
+We would want to allow C to be rebased, refuse A, and encourage
+B to be deleted.
+
+To compute (1):
+
+	git rev-list ^master ^topic next
+	git rev-list ^master        next
+
+	if these match, topic has not merged in next at all.
+
+To compute (2):
+
+	git rev-list master..topic
+
+	if this is empty, it is fully merged to "master".
