Whoever said, ''It's not whether you win or lose that counts,'' probably lost. -- Martina Navratilova

diff --git a/443d31bff54b4e07aa5c7fe8eafb6d0b b/443d31bff54b4e07aa5c7fe8eafb6d0b
--- a/443d31bff54b4e07aa5c7fe8eafb6d0b
+++ b/443d31bff54b4e07aa5c7fe8eafb6d0b
@@ -1,17 +1,51 @@
-2020年  9月  6日 日曜日 10:04:05 JST
-Release 8.1.03i - par I.27
-Copyright (c) 1995-2005 Xilinx, Inc.  All rights reserved.
+2020年  9月  6日 日曜日 11:08:49 JST
+#!/bin/sh
+#
+# An example hook script to verify what is about to be committed.
+# Called by "git commit" with no arguments.  The hook should
+# exit with non-zero status after issuing an appropriate message if
+# it wants to stop the commit.
+#
+# To enable this hook, rename this file to "pre-commit".
 
-Sun Nov 19 22:38:31 2006
+if git rev-parse --verify HEAD >/dev/null 2>&1
+then
+	against=HEAD
+else
+	# Initial commit: diff against an empty tree object
+	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
+fi
 
-There are 0 unrouted networks: 
+# If you want to allow non-ascii filenames set this variable to true.
+allownonascii=$(git config hooks.allownonascii)
 
+# Redirect output to stderr.
+exec 1>&2
 
-There are 6 sourceless or loadless networks: 
+# Cross platform projects tend to avoid non-ascii filenames; prevent
+# them from being added to the repository. We exploit the fact that the
+# printable range starts at the space character and ends with tilde.
+if [ "$allownonascii" != "true" ] &&
+	# Note that the use of brackets around a tr range is ok here, (it's
+	# even required, for portability to Solaris 10's /usr/bin/tr), since
+	# the square bracket bytes happen to fall in the designated range.
+	test $(git diff --cached --name-only --diff-filter=A -z $against |
+	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
+then
+	echo "Error: Attempt to add a non-ascii file name."
+	echo
+	echo "This can cause problems if you want to work"
+	echo "with people on other platforms."
+	echo
+	echo "To be portable it is advisable to rename the file ..."
+	echo
+	echo "If you know what you are doing you can disable this"
+	echo "check using:"
+	echo
+	echo "  git config hooks.allownonascii true"
+	echo
+	exit 1
+fi
 
-   CBUS<2>_IBUF
-   CBUS<3>_IBUF
-   CBUS<4>_IBUF
-   CBUS<5>_IBUF
-   CBUS<6>_IBUF
-   FPGA_NO<2>_IBUF
+# If there are whitespace errors, print the offending file names and fail.
+exec git diff-index --check --cached $against --
