Man lives freely only by his readiness to die. -- Mahatma Gandhi

diff --git a/62202eb218ad49a685da7a322e465c79 b/62202eb218ad49a685da7a322e465c79
--- a/62202eb218ad49a685da7a322e465c79
+++ b/62202eb218ad49a685da7a322e465c79
@@ -1,20 +1,54 @@
-2024年  8月 12日 月曜日 11:52:28 JST
-#!/usr/bin/perl
+2024年  8月 17日 土曜日 09:42:57 JST
+#!/bin/sh
 
+# An example hook script to verify what is about to be pushed.  Called by "git
+# push" after it has checked the remote status, but before anything has been
+# pushed.  If this script exits with a non-zero status nothing will be pushed.
+#
+# This hook is called with the following parameters:
+#
+# $1 -- Name of the remote to which the push is being done
+# $2 -- URL to which the push is being done
+#
+# If pushing without using a named remote those arguments will be equal.
+#
+# Information about the commits which are being pushed is supplied as lines to
+# the standard input in the form:
+#
+#   <local ref> <local sha1> <remote ref> <remote sha1>
+#
+# This sample shows how to prevent push of commits where the log message starts
+# with "WIP" (work in progress).
 
-my $is_stop = 0;
+remote="$1"
+url="$2"
 
-if($ARGV[0]){
-    $is_stop = 1;
-}
+z40=0000000000000000000000000000000000000000
 
-my $cmd ="cat /sys/class/fpga/fpga0/irq_count";
+IFS=' '
+while read local_ref local_sha remote_ref remote_sha
+do
+	if [ "$local_sha" = $z40 ]
+	then
+		# Handle delete
+	else
+		if [ "$remote_sha" = $z40 ]
+		then
+			# New branch, examine all commits
+			range="$local_sha"
+		else
+			# Update to existing branch, examine new commits
+			range="$remote_sha..$local_sha"
+		fi
 
-while(1){
-    my $exe = `$cmd`;
-    print $exe;
-    exit (1) if($is_stop == 1);
-    sleep (2);
-}
+		# Check for WIP commit
+		commit=`git rev-list -n 1 --grep '^WIP' "$range"`
+		if [ -n "$commit" ]
+		then
+			echo "Found WIP commit in $local_ref, not pushing"
+			exit 1
+		fi
+	fi
+done
 
-1;
+exit 0
