Only the gentle are ever really strong. -- James Dean

diff --git a/77bcd7bdbc25433fa4c680592c4fddda b/77bcd7bdbc25433fa4c680592c4fddda
--- a/77bcd7bdbc25433fa4c680592c4fddda
+++ b/77bcd7bdbc25433fa4c680592c4fddda
@@ -1,158 +1,170 @@
-Sat Nov  3 19:50:45 JST 2012
-#define ERROR_CHECK
+Sun Nov 11 20:16:21 JST 2012
+#!/bin/sh
+#
+# Copyright (c) 2006, 2008 Junio C Hamano
+#
+# The "pre-rebase" hook is run just before "git rebase" starts doing
+# its job, and can prevent the command from running by exiting with
+# non-zero status.
+#
+# The hook is called with the following parameters:
+#
+# $1 -- the upstream the series was forked from.
+# $2 -- the branch being rebased (or empty when rebasing the current branch).
+#
+# This sample shows how to prevent topic branches that are already
+# merged to 'next' branch from getting rebased, because allowing it
+# would result in rebasing already published history.
 
-#include <iostream>
-using namespace std;
-#include <fstream>
-#include <stdlib.h>
-#include <stdio.h>
-#include <string.h>
-#include <math.h>
+publish=next
+basebranch="$1"
+if test "$#" = 2
+then
+	topic="refs/heads/$2"
+else
+	topic=`git symbolic-ref HEAD` ||
+	exit 0 ;# we do not interrupt rebasing detached HEAD
+fi
 
-#define NMAX (1<<17) // 131072
+case "$topic" in
+refs/heads/??/*)
+	;;
+*)
+	exit 0 ;# we do not interrupt others.
+	;;
+esac
 
-extern "C" void force(double xj[][3], double mj[], double xi[][3], double eps2, double a[][3], int ni, int nj);
+# Now we are dealing with a topic branch being rebased
+# on top of master.  Is it OK to rebase it?
 
-#include <time.h>
-#include <unistd.h>
-#include <sys/time.h>
-#include <sys/resource.h>
-double get_time(void)
-{
-  struct rusage r;
-  double sec, usec, z;
-  getrusage(RUSAGE_SELF, &r);
-  sec   = r.ru_utime.tv_sec;
-  usec  = r.ru_utime.tv_usec;
-  z = sec + usec*1.0e-6;
-  return (z);
+# Does the topic really exist?
+git show-ref -q "$topic" || {
+	echo >&2 "No such branch $topic"
+	exit 1
 }
 
-static double r[NMAX][3];
-static double m[NMAX];
-static double eps2 = 0.0001;
-static double a[NMAX][3];
-static double v[NMAX][3];
-static double a_h[NMAX][3];
+# Is topic fully merged to master?
+not_in_master=`git rev-list --pretty=oneline ^master "$topic"`
+if test -z "$not_in_master"
+then
+	echo >&2 "$topic is fully merged to master; better remove it."
+	exit 1 ;# we could allow it, but there is no point.
+fi
 
-void readfile(char* fname, int* nbody, double* m, double r[][3], double v[][3])
-{
-  ifstream f;
-  f.open(fname, ios::in);
-  if(!f) {
-    cerr << "Can't open file: " <<  fname << endl;
-    exit(-1);
-  }
-  char* buf= new char [2048];
-  f.getline(buf, 511); // *ignore*
-  int n;
-  f >> n;
-  (*nbody) = n;
-  f.getline(buf, 511); // *ignore*
+# Is topic ever merged to next?  If so you should not be rebasing it.
+only_next_1=`git rev-list ^master "^$topic" ${publish} | sort`
+only_next_2=`git rev-list ^master           ${publish} | sort`
+if test "$only_next_1" = "$only_next_2"
+then
+	not_in_topic=`git rev-list "^$topic" master`
+	if test -z "$not_in_topic"
+	then
+		echo >&2 "$topic is already up-to-date with master"
+		exit 1 ;# we could allow it, but there is no point.
+	else
+		exit 0
+	fi
+else
+	not_in_next=`git rev-list --pretty=oneline ^${publish} "$topic"`
+	/usr/bin/perl -e '
+		my $topic = $ARGV[0];
+		my $msg = "* $topic has commits already merged to public branch:\n";
+		my (%not_in_next) = map {
+			/^([0-9a-f]+) /;
+			($1 => 1);
+		} split(/\n/, $ARGV[1]);
+		for my $elem (map {
+				/^([0-9a-f]+) (.*)$/;
+				[$1 => $2];
+			} split(/\n/, $ARGV[2])) {
+			if (!exists $not_in_next{$elem->[0]}) {
+				if ($msg) {
+					print STDERR $msg;
+					undef $msg;
+				}
+				print STDERR " $elem->[1]\n";
+			}
+		}
+	' "$topic" "$not_in_next" "$not_in_master"
+	exit 1
+fi
 
-  f.scientific;
-  for(int i=0; i<n; i++){
-    f.getline(buf, 1024);
-    char ii[256];
-    double mj, x, y, z, vx, vy, vz;
-    f >> ii >> mj >> x >> y >> z >> vx >> vy >> vz;
-    //    printf("%s   %.16E   % .16E % .16E % .16E   % .16E % .16E % .16E \n", ii, m, x, y, z, vx, vy, vz);
-    m[i]    = mj;
-    r[i][0] = x;
-    r[i][1] = y;
-    r[i][2] = z;
-    v[i][0] = vx;
-    v[i][1] = vy;
-    v[i][2] = vz;
-  }
-  f.close();
+exit 0
 
-  delete[] buf;
-}
+################################################################
 
-void force_host(double xj[][3],
-								double m[],
-								double xi[][3],
-								double eps2,
-								double a[][3],
-								int ni,
-								int nj)
-{
-  int i,j,d;
-  double dx[3];
-  for(i=0;i<ni;i++) for(d=0;d<3;d++) a[i][d] = 0.0;
+This sample hook safeguards topic branches that have been
+published from being rewound.
 
-  for(i=0;i<ni;i++){
-    for(j=0;j<nj;j++){
-      double r2,r3;
-      r2 = eps2;
-      for(d=0;d<3;d++){
-				dx[d] = xj[j][d] - xi[i][d];
-				r2 += dx[d] * dx[d];
-      }
-      r3 = sqrt(r2)*r2;
-      for(d=0;d<3;d++){
-				a[i][d] +=  m[j]*dx[d]/r3;
-      }
-    }
-  }
-}
+The workflow assumed here is:
 
-int main(int argc,char** argv)
-{
-  int n=0;
-  int nstep = 1;
+ * Once a topic branch forks from "master", "master" is never
+   merged into it again (either directly or indirectly).
 
-  if((argc == 2)||(argc == 3)){
-    char ifile[256];
-    strcpy(ifile,argv[1]);
-    readfile(ifile, &n, m, r, v);
-    if(argc == 3)  nstep = atoi(argv[2]);
-  }else{
-    fprintf(stderr, "argc = %d\n",argc);
-    fprintf(stderr, "cmd <init file> <nstep>\n");
-    exit(-1);
-  }
+ * Once a topic branch is fully cooked and merged into "master",
+   it is deleted.  If you need to build on top of it to correct
+   earlier mistakes, a new topic branch is created by forking at
+   the tip of the "master".  This is not strictly necessary, but
+   it makes it easier to keep your history simple.
 
-  int ni=n;
-  int nj=n;
+ * Whenever you need to test or publish your changes to topic
+   branches, merge them into "next" branch.
 
-  force(r, m, r, eps2, a, ni, nj);
+The script, being an example, hardcodes the publish branch name
+to be "next", but it is trivial to make it configurable via
+$GIT_DIR/config mechanism.
 
-  double eps2 = (1./256.);
-  double tt = get_time();
-  for(int step = 0; step < nstep; step++) force(r, m, r, eps2, a, ni, nj);
-  tt = get_time() - tt;
+With this workflow, you would want to know:
 
-  double nfloat = 38.0 * ((double)ni)*((double)nj) * ((double)nstep);
-  double gflops = nfloat * (1.e-9) / tt;
-  //  fprintf(stdout, "n=%d\t%g sec/gpucall\t%g Gflops\n", n, tt/(double)nstep, gflops );
-  fprintf(stdout, "n=%d\n", n);
-  fprintf(stdout, "%g sec/gpucall\n", tt/(double)nstep);
-  fprintf(stdout, "%g Gflops\n",  gflops );
+(1) ... if a topic branch has ever been merged to "next".  Young
+    topic branches can have stupid mistakes you would rather
+    clean up before publishing, and things that have not been
+    merged into other branches can be easily rebased without
+    affecting other people.  But once it is published, you would
+    not want to rewind it.
+
+(2) ... if a topic branch has been fully merged to "master".
+    Then you can delete it.  More importantly, you should not
+    build on top of it -- other people may already want to
+    change things related to the topic as patches against your
+    "master", so if you need further changes, it is better to
+    fork the topic (perhaps with the same name) afresh from the
+    tip of "master".
+
+Let's look at this example:
+
+		   o---o---o---o---o---o---o---o---o---o "next"
+		  /       /           /           /
+		 /   a---a---b A     /           /
+		/   /               /           /
+	       /   /   c---c---c---c B         /
+	      /   /   /             \         /
+	     /   /   /   b---b C     \       /
+	    /   /   /   /             \     /
+    ---o---o---o---o---o---o---o---o---o---o---o "master"
 
 
-  if(0){
-    cout << "Start Error check: " << n <<endl;
-    force_host(r, m, r, eps2, a_h, ni, nj);
-    double err_max = 0.0;
-    for(int i=0;i<ni;i++){
-      double err=0.0;
-      for(int d=0;d<3;d++){
-				double diff = fabs(a[i][d] - a_h[i][d]);
-				err += (diff*diff);
-      }
-      err = sqrt(err);
-      err = err/sqrt(a_h[i][0]*a_h[i][0]+a_h[i][1]*a_h[i][1]+a_h[i][2]*a_h[i][2]);
-      if (err > err_max){
-				err_max = err;
-				printf("[%d]:\t", i);
-				printf("%.7e:\t", err);
-				printf("%e,%e,%e:\t%e,%e,%e\n",a_h[i][0], a_h[i][1], a_h[i][2],a[i][0], a[i][1], a[i][2]);
-      }
-    }
-    printf("Max Err %.7e\n", err_max);
-  }
+A, B and C are topic branches.
 
-  return (0);
-}
+ * A has one fix since it was merged up to "next".
+
+ * B has finished.  It has been fully merged up to "master" and "next",
+   and is ready to be deleted.
+
+ * C has not merged to "next" at all.
+
+We would want to allow C to be rebased, refuse A, and encourage
+B to be deleted.
+
+To compute (1):
+
+	git rev-list ^master ^topic next
+	git rev-list ^master        next
+
+	if these match, topic has not merged in next at all.
+
+To compute (2):
+
+	git rev-list master..topic
+
+	if this is empty, it is fully merged to "master".
