If one advances confidently in the direction of his dreams, and endeavors to live the life which he has imagined, he will meet with a success unexpected in common hours. -- Henry David Thoreau

diff --git a/7fa9716e58124b3fa65630db6a8882c1 b/7fa9716e58124b3fa65630db6a8882c1
--- a/7fa9716e58124b3fa65630db6a8882c1
+++ b/7fa9716e58124b3fa65630db6a8882c1
@@ -1,47 +1,25 @@
-2023年  7月 25日 火曜日 10:40:42 JST
-#include <stdio.h>
-#include <string.h>
-#include <stdlib.h>
+2023年  7月 26日 水曜日 11:44:42 JST
+#!/bin/sh
+#
+# An example hook script to check the commit log message.
+# Called by "git commit" with one argument, the name of the file
+# that has the commit message.  The hook should exit with non-zero
+# status after issuing an appropriate message if it wants to stop the
+# commit.  The hook is allowed to edit the commit message file.
+#
+# To enable this hook, rename this file to "commit-msg".
 
-/*
- * ifpga_get_barinfo.c -- to get infomation of pci bar regsters
- *
- * Copyright (C) 2006-2007 Tsuyoshi Hamada
- *                                All rights reserved.
- * 
- * No warranty is attached; 
- * I cannot take responsibility for errors or fitness for use.
- *
- */
+# Uncomment the below to add a Signed-off-by line to the message.
+# Doing this in a hook is a bad idea in general, but the prepare-commit-msg
+# hook is more suited to it.
+#
+# SOB=$(git var GIT_AUTHOR_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
+# grep -qs "^$SOB" "$1" || echo "$SOB" >> "$1"
 
-#include "pg4.h"
+# This example catches duplicate Signed-off-by lines.
 
-int main(int argc, char* argv[])
-{
-  int devid  = 0;
-  int bar    = 0;
-  int is_size = 0;
-  unsigned long z = 0;
-
-  if (argc < 3) {
-    fprintf(stderr, "%s <devid> <bar_num> <adr=0/size=1>\n", argv[0]);
-    exit(-1);
-  }
-  
-  if(argc == 3) is_size = 0; else is_size = atoi(argv[3]);
-
-  devid = atoi(argv[1]);
-  bar   = atoi(argv[2]);
-  
-  pg4_open(devid);
-
-  if(is_size)
-    z = 0xffffffff & pg4_getbaseaddr_size(devid, bar);
-  else
-    z = 0xffffffff & pg4_getbaseaddr(devid, bar);
-
-  printf("0x%08lx\n",z);
-  pg4_close(devid);
-
-  return 1;
+test "" = "$(grep '^Signed-off-by: ' "$1" |
+	 sort | uniq -c | sed -e '/^[ 	]*1[ 	]/d')" || {
+	echo >&2 Duplicate Signed-off-by lines.
+	exit 1
 }
