To live is to climb the Andes: the more one climbs, the steeper become the precipices. -- Eucenio Maria De Hostos

diff --git a/83ee8560ac864ca28100269a52db61f2 b/83ee8560ac864ca28100269a52db61f2
--- a/83ee8560ac864ca28100269a52db61f2
+++ b/83ee8560ac864ca28100269a52db61f2
@@ -1,34 +1,25 @@
-Tue Sep 21 19:30:07 JST 2010
--- Copyright 2004 Tsuyoshi Hamada
---
---
---clk         __~~ __~~ __~~ __~~ __~~ __~~ __~~ __~~ __~~ __~~ __~~ __~~ __~~ __~~ __
---state_dmaw          0  >< 1 >< 2                                    >< 3 >< 0 
---mem_we                        ____/~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\______
+Fri Nov  5 19:50:51 JST 2010
+#!/bin/sh
+#
+# An example hook script to check the commit log message.
+# Called by "git commit" with one argument, the name of the file
+# that has the commit message.  The hook should exit with non-zero
+# status after issuing an appropriate message if it wants to stop the
+# commit.  The hook is allowed to edit the commit message file.
+#
+# To enable this hook, rename this file to "commit-msg".
 
-library IEEE;
-use IEEE.STD_LOGIC_1164.ALL;
-use IEEE.STD_LOGIC_UNSIGNED.ALL;
+# Uncomment the below to add a Signed-off-by line to the message.
+# Doing this in a hook is a bad idea in general, but the prepare-commit-msg
+# hook is more suited to it.
+#
+# SOB=$(git var GIT_AUTHOR_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
+# grep -qs "^$SOB" "$1" || echo "$SOB" >> "$1"
 
-entity dmaw_mem_we is
-  port (
-    CLK       : in std_logic;
-    STATE     : in std_logic_vector(1 downto 0);
-    MEM_WE    : out std_logic );
-end dmaw_mem_we;
+# This example catches duplicate Signed-off-by lines.
 
-architecture rtl of dmaw_mem_we is
-
-begin
-
-  process (CLK,STATE) begin
-    if(CLK'event and CLK = '1') then
-      if(STATE="10") then
-        MEM_WE <= '1';
-      else
-        MEM_WE <= '0';
-      end if;
-    end if;
-  end process;
-
-end rtl;
+test "" = "$(grep '^Signed-off-by: ' "$1" |
+	 sort | uniq -c | sed -e '/^[ 	]*1[ 	]/d')" || {
+	echo >&2 Duplicate Signed-off-by lines.
+	exit 1
+}
