It always seems impossible until it's done -- Nelson Mandela

diff --git a/861cde128d3449c0ba0b4bd7370e1066 b/861cde128d3449c0ba0b4bd7370e1066
--- a/861cde128d3449c0ba0b4bd7370e1066
+++ b/861cde128d3449c0ba0b4bd7370e1066
@@ -1,57 +1,25 @@
-2021年 11月  4日 木曜日 10:30:45 JST
--- 2005/06/13
-#define NPOS 32
-#define NLOG 17
-#define NMAN 8
-#define NCUT 6
-#define NFOR 57
-#define NACC 64
-#define D_FSU  1
-#define D_FTL  2
-#define D_LAD  4
-#define D_LMU  1
-#define D_LTF  2
-#define D_FAC  1
+2021年 11月 28日 日曜日 09:36:20 JST
+#!/bin/sh
+#
+# An example hook script to check the commit log message.
+# Called by "git commit" with one argument, the name of the file
+# that has the commit message.  The hook should exit with non-zero
+# status after issuing an appropriate message if it wants to stop the
+# commit.  The hook is allowed to edit the commit message file.
+#
+# To enable this hook, rename this file to "commit-msg".
 
-// -1 < xbox < 1.0,
-// mmin > 1.0 (1e-2 < m < 1.0 ==> underflow around large R)
-#define xsize (2.0)
-#define mmin  (1.0e-2)
-#define xscale (pow(2.0,(double)NPOS)/xsize)
-//mmin 0xdf61
-#define mscale (pow(2.0,95.38)/mmin)
-#define escale (xscale*xscale)
+# Uncomment the below to add a Signed-off-by line to the message.
+# Doing this in a hook is a bad idea in general, but the prepare-commit-msg
+# hook is more suited to it.
+#
+# SOB=$(git var GIT_AUTHOR_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
+# grep -qs "^$SOB" "$1" || echo "$SOB" >> "$1"
 
-#define NEXAD -31
-#define fshift pow(2.0,-1.0*(double)NEXAD)
-#define fscale (-xscale*xscale*fshift/mscale)
+# This example catches duplicate Signed-off-by lines.
 
-/NPIPE 2;
-/NVMP 1;
-
-/JPSET xj[3], x[][], fix,      NPOS,xscale;
-/JPSET mj,    m[],   log,      NLOG,NMAN,mscale;
-/IPSET xi[3], x[][], fix,      NPOS,xscale;
-/IPSET ieps2, eps2,  log,      NLOG,NMAN,escale;
-/FOSET sx[3], a[][], fix,      NACC,fscale;
-
-pg_fix_addsub(SUB,xi,xj,xij,           NPOS,           D_FSU);
-pg_conv_ftol(xij,dx,                   NPOS,NLOG,NMAN, D_FTL);
-pg_log_shift(1,dx,x2,                  NLOG);
-
---pg_log_unsigned_add_itp(x2[0],x2[1], x2y2,   NLOG,NMAN,  D_LAD,NCUT);
---pg_log_unsigned_add_itp(x2[2],ieps2, z2e2,   NLOG,NMAN,  D_LAD,NCUT);
---pg_log_unsigned_add_itp(x2y2,z2e2,   r2,     NLOG,NMAN,  D_LAD,NCUT);
-pg_log_unsigned_add(x2[0],x2[1], x2y2, NLOG,NMAN,      D_LAD);
-pg_log_unsigned_add(x2[2],ieps2, z2e2, NLOG,NMAN,      D_LAD);
-pg_log_unsigned_add(x2y2,z2e2,   r2,   NLOG,NMAN,      D_LAD);
-
-pg_log_shift(-1,r2,       r1,          NLOG);
-pg_log_muldiv(MUL,r2,r1,  r3,          NLOG,           D_LMU);
-pg_log_muldiv(SDIV,mj,r3,  mf,         NLOG,           D_LMU);
-pg_log_muldiv(MUL,mf,dx,  fx,          NLOG,           D_LMU);
---pg_log_muldiv(SDIV,fx,f_shift, fxs,    NLOG,           D_LMU);
-pg_log_expadd(fx,fxs,                  NEXAD,NLOG,NMAN, D_LMU);
-
-pg_conv_ltof(fxs,  ffx,                NLOG,NMAN,NFOR, D_LTF);
-pg_fix_accum(ffx,  sx,                 NFOR,NACC,      D_FAC);
+test "" = "$(grep '^Signed-off-by: ' "$1" |
+	 sort | uniq -c | sed -e '/^[ 	]*1[ 	]/d')" || {
+	echo >&2 Duplicate Signed-off-by lines.
+	exit 1
+}
