Stay hungry. Stay foolish. -- Steve Jobs

diff --git a/907ffe808365436d99441a83a45f7106 b/907ffe808365436d99441a83a45f7106
--- a/907ffe808365436d99441a83a45f7106
+++ b/907ffe808365436d99441a83a45f7106
@@ -1,28 +1,25 @@
-2022年 10月  8日 土曜日 10:45:16 JST
-// Copyright(c) 2004- by PGPG
-// The original source : contrib/src_h/vi/pg_util.h
-#include <stdio.h>
-#include <stdlib.h>
-#include <time.h>
-#include <math.h>
-#ifndef LONG
-#define LONG unsigned long long int
-#endif
-LONG  double2pgpglog(double x, int nbit_log, int nbit_man);
-double pgpglog2double(LONG x,  int nbit_log, int nbit_man);
-LONG  double2pgpgfloat(double a, int nbit_float, int nbit_man);
-LONG  double2pgpgfloat_r(double a, int nbit_float, int nbit_man, int rmode);
-double pgpgfloat2double(LONG x, int nbit_float, int nbit_man);
-LONG extractbit_long(LONG in, int hi, int lo);
-void l2bit(LONG a);
-void putbits(LONG a);
-void putbits32(LONG a);
-void putbitsn(LONG a,int n);
-double gen_rand_abs(void);
-double gen_rand(void);
-double gen_rand_tamanizero(void);
+2022年 10月 16日 日曜日 11:09:42 JST
+#!/bin/sh
+#
+# An example hook script to check the commit log message.
+# Called by "git commit" with one argument, the name of the file
+# that has the commit message.  The hook should exit with non-zero
+# status after issuing an appropriate message if it wants to stop the
+# commit.  The hook is allowed to edit the commit message file.
+#
+# To enable this hook, rename this file to "commit-msg".
 
+# Uncomment the below to add a Signed-off-by line to the message.
+# Doing this in a hook is a bad idea in general, but the prepare-commit-msg
+# hook is more suited to it.
+#
+# SOB=$(git var GIT_AUTHOR_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
+# grep -qs "^$SOB" "$1" || echo "$SOB" >> "$1"
 
-#include <sys/time.h>
-#include <sys/resource.h>
-double e_time(void);
+# This example catches duplicate Signed-off-by lines.
+
+test "" = "$(grep '^Signed-off-by: ' "$1" |
+	 sort | uniq -c | sed -e '/^[ 	]*1[ 	]/d')" || {
+	echo >&2 Duplicate Signed-off-by lines.
+	exit 1
+}
