Only put off until tomorrow what you are willing to die having left undone. -- Pablo Picasso

diff --git a/9ce59b8a0db34932ba7f884b2e3652f5 b/9ce59b8a0db34932ba7f884b2e3652f5
--- a/9ce59b8a0db34932ba7f884b2e3652f5
+++ b/9ce59b8a0db34932ba7f884b2e3652f5
@@ -1,172 +1,170 @@
-Sun Nov 30 19:29:53 JST 2014
--- LOCAL READ CONTROLLER ( ifpga <- pfpga )
--- (LOCAL_READ_IFに開始信号を全チップ回数分送るモジュール)
--- by Tsuyoshi Hamada 2005/01/04
--- メモ : 
---   NQWORDとってくるのに必要なLOCAL_READ_IFのクロック(BUSY) : NQWORD + 8(レイテンシ:INTF_LAT) クロック
--- 
--- (0) IFに START_AD, NQWORD をセット     : 1クロック
--- (1) IFに CHIPSEL, MEM_AD_BASE をセット : 1クロック
--- (2) IFの EXEC を上げる                 : 1クロック
--- (3) IFに EXEC を下げる                 : 1クロック
--- (4) IFが転送を終了するまで待つ         : I_NC クロック(I_NC= NPIPE*pow(2,NBIT_L_ADRO)
--- (5) (1)から(4)までを4チップ分繰り返す.
---
--- (※) LOCAL_READ_IFの転送に必要なクロックは決まっているので転送終了フラグは見ない.
--- (※) l_adroのビット幅(NBIT_L_ADRO)を変えた場合はpromを焼きなおす必要があることに注意.(直すのは上のモジュール)
+Thu Dec 18 19:47:42 JST 2014
+#!/bin/sh
+#
+# Copyright (c) 2006, 2008 Junio C Hamano
+#
+# The "pre-rebase" hook is run just before "git rebase" starts doing
+# its job, and can prevent the command from running by exiting with
+# non-zero status.
+#
+# The hook is called with the following parameters:
+#
+# $1 -- the upstream the series was forked from.
+# $2 -- the branch being rebased (or empty when rebasing the current branch).
+#
+# This sample shows how to prevent topic branches that are already
+# merged to 'next' branch from getting rebased, because allowing it
+# would result in rebasing already published history.
 
-library IEEE;
-use IEEE.STD_LOGIC_1164.ALL;
-use IEEE.STD_LOGIC_UNSIGNED.ALL;
-use IEEE.STD_LOGIC_ARITH.ALL;
+publish=next
+basebranch="$1"
+if test "$#" = 2
+then
+	topic="refs/heads/$2"
+else
+	topic=`git symbolic-ref HEAD` ||
+	exit 0 ;# we do not interrupt rebasing detached HEAD
+fi
 
-entity LOCAL_READ_CNT is
-  generic (
-           CNT_WIDTH     : integer := 16;      -- program counter bit-width
-           FO_BASE       : integer := 24576;   -- = 0x6000
-           NBIT_L_ADRO   : integer := 3;       -- Bit-Length of l_ado(pgpg_mem.vhd)
-           INTF_LAT      : integer := 8        -- LOCAL_READ_IF latency (clock)
-  );
-  port (
-    -- from LOCAL_READ
-    NPIPE : in std_logic_vector(7 downto 0);     -- number of pipelines per chip
-    -- from LOCAL_READ_DONE
-    CALC_DONE  : in std_logic;   -- pulse
-    -- to LOCAL_READ_DONE
-    FETCH_DONE : out std_logic;  -- pulse
+case "$topic" in
+refs/heads/??/*)
+	;;
+*)
+	exit 0 ;# we do not interrupt others.
+	;;
+esac
 
-    -- to LOCAL_READ_IF
-    EXEC     : out std_logic;                     -- pulse
-    START_AD : out std_logic_vector(18 downto 0); -- 19 bit
-    NQWORD   : out std_logic_vector( 8 downto 0); --  9 bit
-    CHIPSEL  : out std_logic_vector( 3 downto 0); --  4 bit
-    MEM_AD_BASE : out std_logic_vector(12 downto 0);
-    -- from LOCAL_READ_IF
---    BUSY_IF : in std_logic;
- 
-    RST : in  std_logic;
-    CLK : in  std_logic
-    );
-end LOCAL_READ_CNT;
+# Now we are dealing with a topic branch being rebased
+# on top of master.  Is it OK to rebase it?
 
-architecture rtl of LOCAL_READ_CNT is
+# Does the topic really exist?
+git show-ref -q "$topic" || {
+	echo >&2 "No such branch $topic"
+	exit 1
+}
 
-signal hit0,hit1 : std_logic :='0';
-signal cnt,cntr : std_logic_vector(CNT_WIDTH-1 downto 0) :=(others=>'0');
-signal cnt_en : std_logic :='0';
-signal is_finish,is_finishr : std_logic :='0';
+# Is topic fully merged to master?
+not_in_master=`git rev-list --pretty=oneline ^master "$topic"`
+if test -z "$not_in_master"
+then
+	echo >&2 "$topic is fully merged to master; better remove it."
+	exit 1 ;# we could allow it, but there is no point.
+fi
 
-----
-signal c_start_ad   : std_logic_vector(18 downto 0) :=(others=>'0');
-signal c_nqword     : std_logic_vector(18 downto 0) :=(others=>'0');
-signal c_chipsel    : std_logic_vector(18 downto 0) :=(others=>'0');
-signal c_mem_offset : std_logic_vector(18 downto 0) :=(others=>'0');
-begin
+# Is topic ever merged to next?  If so you should not be rebasing it.
+only_next_1=`git rev-list ^master "^$topic" ${publish} | sort`
+only_next_2=`git rev-list ^master           ${publish} | sort`
+if test "$only_next_1" = "$only_next_2"
+then
+	not_in_topic=`git rev-list "^$topic" master`
+	if test -z "$not_in_topic"
+	then
+		echo >&2 "$topic is already up-to-date with master"
+		exit 1 ;# we could allow it, but there is no point.
+	else
+		exit 0
+	fi
+else
+	not_in_next=`git rev-list --pretty=oneline ^${publish} "$topic"`
+	/usr/bin/perl -e '
+		my $topic = $ARGV[0];
+		my $msg = "* $topic has commits already merged to public branch:\n";
+		my (%not_in_next) = map {
+			/^([0-9a-f]+) /;
+			($1 => 1);
+		} split(/\n/, $ARGV[1]);
+		for my $elem (map {
+				/^([0-9a-f]+) (.*)$/;
+				[$1 => $2];
+			} split(/\n/, $ARGV[2])) {
+			if (!exists $not_in_next{$elem->[0]}) {
+				if ($msg) {
+					print STDERR $msg;
+					undef $msg;
+				}
+				print STDERR " $elem->[1]\n";
+			}
+		}
+	' "$topic" "$not_in_next" "$not_in_master"
+	exit 1
+fi
 
-  FETCH_DONE <= is_finish; -- transfer done pulse
+exit 0
 
-  hit0 <= CALC_DONE;
-  process (CLK) begin
-    if (CLK'event and CLK='1') then
-      is_finishr <= is_finish;
-      hit1 <= hit0;
-    end if;
-  end process;
+################################################################
 
-  -- PROGRAM COUNTER
-  cntr <= cnt + conv_std_logic_vector(1, CNT_WIDTH);
-  process (RST,CLK,hit0,hit1,cnt_en) begin
-    if (RST = '1') then
-      cnt <= (others=>'0');
-    elsif (CLK'event and CLK='1') then
-      if((hit0 = '1') AND (hit1 = '0')) then
-        cnt <= (others=>'0');
-      elsif(cnt_en = '1') then
-        cnt <= cntr;
-      end if;
-    end if;
-  end process;
+This sample hook safeguards topic branches that have been
+published from being rewound.
 
-  -- COUNTER ENABLE (counting up signal)
-  process (RST,CLK,hit0,hit1,is_finish,is_finishr) begin
-    if (RST = '1') then
-      cnt_en <= '0';
-    elsif (CLK'event and CLK='1') then
-      if((hit0 = '1') AND (hit1 = '0')) then
-        cnt_en <= '1';
-      elsif((is_finish = '1') AND (is_finishr = '0')) then
-        cnt_en <= '0';
-      end if;
-    end if;
-  end process;
+The workflow assumed here is:
 
-  ------------------------------------------------------------- PROGRAM
-  process (RST,CLK,cnt)
-      variable I_NPIPE : integer;
-      variable I_NFI   : integer;
-      variable I_NC    : integer;
-      variable I_MAB   : integer;
-      variable I_NQW   : integer;
-  begin
-    if (RST='1') then
-      is_finish <= '0';
-    elsif (CLK'event and CLK='1') then
+ * Once a topic branch forks from "master", "master" is never
+   merged into it again (either directly or indirectly).
 
-      --= = = = = = = = = = = = = = = = = = = = INTEGER VARLUES
-      I_NPIPE := conv_integer(NPIPE);
-      I_NFI   := (2**NBIT_L_ADRO);
---      I_NFI   := (2**2);  -- トップからのジェネリックの伝播がうまくいきませんので注意
-      I_NC    := I_NPIPE*I_NFI + INTF_LAT;
-      I_MAB   := I_NPIPE*I_NFI;
-      I_NQW   := I_NPIPE*I_NFI - 1;
-      --= = = = = = = = = = = = = = = = = = = = = = = = = = = =
+ * Once a topic branch is fully cooked and merged into "master",
+   it is deleted.  If you need to build on top of it to correct
+   earlier mistakes, a new topic branch is created by forking at
+   the tip of the "master".  This is not strictly necessary, but
+   it makes it easier to keep your history simple.
 
-      if(    cnt = conv_std_logic_vector(0, CNT_WIDTH) ) then
-        is_finish <= '0';
-        NQWORD   <= conv_std_logic_vector(I_NQW, 9);
-        START_AD <= conv_std_logic_vector(FO_BASE, 19);
-      -- ================================================================================ CHIP 0
-      elsif( cnt = conv_std_logic_vector(1, CNT_WIDTH) ) then
-        MEM_AD_BASE <= conv_std_logic_vector(0, 13);
-        CHIPSEL  <= "0001";
-      elsif( cnt = conv_std_logic_vector(2, CNT_WIDTH) ) then
-        EXEC <= '1';
-      elsif( cnt = conv_std_logic_vector(3, CNT_WIDTH) ) then
-        EXEC <= '0';
-      -- ================================================================================ CHIP 1
-      elsif( cnt = conv_std_logic_vector(3 + 1*I_NC, CNT_WIDTH) ) then
-        MEM_AD_BASE <= conv_std_logic_vector(1*I_MAB  , 13);
-        CHIPSEL  <= "0010";
-      elsif( cnt = conv_std_logic_vector(4 + 1*I_NC, CNT_WIDTH) ) then
-        EXEC <= '1';
-      elsif( cnt = conv_std_logic_vector(5 + 1*I_NC, CNT_WIDTH) ) then
-        EXEC <= '0';
-      -- ================================================================================ CHIP 2
-      elsif( cnt = conv_std_logic_vector(5 + 2*I_NC, CNT_WIDTH) ) then
-        MEM_AD_BASE <= conv_std_logic_vector(2*I_MAB, 13);
-        CHIPSEL  <= "0100";
-      elsif( cnt = conv_std_logic_vector(6 + 2*I_NC, CNT_WIDTH) ) then
-        EXEC <= '1';
-      elsif( cnt = conv_std_logic_vector(7 + 2*I_NC, CNT_WIDTH) ) then
-        EXEC <= '0';
-      -- ================================================================================ CHIP 3
-      elsif( cnt = conv_std_logic_vector(7 + 3*I_NC, CNT_WIDTH) ) then
-        MEM_AD_BASE <= conv_std_logic_vector(3*I_MAB, 13);
-        CHIPSEL  <= "1000";
-      elsif( cnt = conv_std_logic_vector(8 + 3*I_NC, CNT_WIDTH) ) then
-        EXEC <= '1';
-      elsif( cnt = conv_std_logic_vector(9 + 3*I_NC, CNT_WIDTH) ) then
-        EXEC <= '0';
-      -- ================================================================================ FINISH
-      elsif( cnt = conv_std_logic_vector(9 + 4*I_NC, CNT_WIDTH) ) then
-        is_finish <= '1';
-      elsif( cnt = conv_std_logic_vector(10 + 4*I_NC, CNT_WIDTH) ) then
-        is_finish <= '0';
-      else
-      end if;
+ * Whenever you need to test or publish your changes to topic
+   branches, merge them into "next" branch.
 
-    end if;
-  end process;
+The script, being an example, hardcodes the publish branch name
+to be "next", but it is trivial to make it configurable via
+$GIT_DIR/config mechanism.
 
-end rtl;
+With this workflow, you would want to know:
 
+(1) ... if a topic branch has ever been merged to "next".  Young
+    topic branches can have stupid mistakes you would rather
+    clean up before publishing, and things that have not been
+    merged into other branches can be easily rebased without
+    affecting other people.  But once it is published, you would
+    not want to rewind it.
+
+(2) ... if a topic branch has been fully merged to "master".
+    Then you can delete it.  More importantly, you should not
+    build on top of it -- other people may already want to
+    change things related to the topic as patches against your
+    "master", so if you need further changes, it is better to
+    fork the topic (perhaps with the same name) afresh from the
+    tip of "master".
+
+Let's look at this example:
+
+		   o---o---o---o---o---o---o---o---o---o "next"
+		  /       /           /           /
+		 /   a---a---b A     /           /
+		/   /               /           /
+	       /   /   c---c---c---c B         /
+	      /   /   /             \         /
+	     /   /   /   b---b C     \       /
+	    /   /   /   /             \     /
+    ---o---o---o---o---o---o---o---o---o---o---o "master"
+
+
+A, B and C are topic branches.
+
+ * A has one fix since it was merged up to "next".
+
+ * B has finished.  It has been fully merged up to "master" and "next",
+   and is ready to be deleted.
+
+ * C has not merged to "next" at all.
+
+We would want to allow C to be rebased, refuse A, and encourage
+B to be deleted.
+
+To compute (1):
+
+	git rev-list ^master ^topic next
+	git rev-list ^master        next
+
+	if these match, topic has not merged in next at all.
+
+To compute (2):
+
+	git rev-list master..topic
+
+	if this is empty, it is fully merged to "master".
