Many of life's failures are people who did not realize how close they were to success when they gave up. -- Thomas Edison

diff --git a/a2311d674c8546c990c59909f4310e37 b/a2311d674c8546c990c59909f4310e37
--- a/a2311d674c8546c990c59909f4310e37
+++ b/a2311d674c8546c990c59909f4310e37
@@ -1,19 +1,51 @@
-2026年  5月  8日 金曜日 10:50:00 JST
-#!Time-stamp: <2007-01-22 04:30:32 hamada>
+2026年  6月 11日 木曜日 11:41:17 JST
+#!/bin/sh
+#
+# An example hook script to verify what is about to be committed.
+# Called by "git commit" with no arguments.  The hook should
+# exit with non-zero status after issuing an appropriate message if
+# it wants to stop the commit.
+#
+# To enable this hook, rename this file to "pre-commit".
 
-Linux device driver for the PROGRAPE-4 board,
+if git rev-parse --verify HEAD >/dev/null 2>&1
+then
+	against=HEAD
+else
+	# Initial commit: diff against an empty tree object
+	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
+fi
 
-including runtime libraries and HDL source for interface FPGA.
+# If you want to allow non-ascii filenames set this variable to true.
+allownonascii=$(git config hooks.allownonascii)
 
-- Linux kernel release 2.6.x
+# Redirect output to stderr.
+exec 1>&2
 
-- Xilinx XC3S5000-5-FG900 FPGAs
+# Cross platform projects tend to avoid non-ascii filenames; prevent
+# them from being added to the repository. We exploit the fact that the
+# printable range starts at the space character and ends with tilde.
+if [ "$allownonascii" != "true" ] &&
+	# Note that the use of brackets around a tr range is ok here, (it's
+	# even required, for portability to Solaris 10's /usr/bin/tr), since
+	# the square bracket bytes happen to fall in the designated range.
+	test $(git diff --cached --name-only --diff-filter=A -z $against |
+	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
+then
+	echo "Error: Attempt to add a non-ascii file name."
+	echo
+	echo "This can cause problems if you want to work"
+	echo "with people on other platforms."
+	echo
+	echo "To be portable it is advisable to rename the file ..."
+	echo
+	echo "If you know what you are doing you can disable this"
+	echo "check using:"
+	echo
+	echo "  git config hooks.allownonascii true"
+	echo
+	exit 1
+fi
 
-- Xilinx ISE 8.1i
--- Release 8.1.03i xst I.27
--- Release 8.1.03i par I.27
--- Release 8.1.03i Trace I.27
--- Release 8.1.03i Bitgen I.27
-
-
-![PROGRAPE-4](http://www.ipa.go.jp/jinzai/esp/2005mito1/mdata/images/clip_image002_006.jpg)
+# If there are whitespace errors, print the offending file names and fail.
+exec git diff-index --check --cached $against --
