Only put off until tomorrow what you are willing to die having left undone. -- Pablo Picasso

diff --git a/a2311d674c8546c990c59909f4310e37 b/a2311d674c8546c990c59909f4310e37
--- a/a2311d674c8546c990c59909f4310e37
+++ b/a2311d674c8546c990c59909f4310e37
@@ -1,53 +1,37 @@
-2024年  1月 16日 火曜日 10:21:24 JST
--- 2005/06/13
-#define NPOS 32
-#define NLOG 17
-#define NMAN 8
-#define NCUT 6
-#define NFOR 57
-#define NACC 64
-#define D_FSU  1
-#define D_FTL  2
-#define D_LAD  4
-#define D_LMU  1
-#define D_LTF  2
-#define D_FAC  1
+2024年  1月 19日 金曜日 09:15:15 JST
+#!/bin/sh
+#
+# An example hook script to prepare the commit log message.
+# Called by "git commit" with the name of the file that has the
+# commit message, followed by the description of the commit
+# message's source.  The hook's purpose is to edit the commit
+# message file.  If the hook fails with a non-zero status,
+# the commit is aborted.
+#
+# To enable this hook, rename this file to "prepare-commit-msg".
 
-// -1 < xbox < 1.0,
-// mmin > 1.0 (1e-2 < m < 1.0 ==> underflow around large R)
-#define xsize (2.0)
-#define mmin  (1.0e-2)
-#define xscale (pow(2.0,(double)NPOS)/xsize)
-//mmin 0xdf61
-#define mscale (pow(2.0,95.38)/mmin)
-#define escale (xscale*xscale)
+# This hook includes three examples.  The first comments out the
+# "Conflicts:" part of a merge commit.
+#
+# The second includes the output of "git diff --name-status -r"
+# into the message, just before the "git status" output.  It is
+# commented because it doesn't cope with --amend or with squashed
+# commits.
+#
+# The third example adds a Signed-off-by line to the message, that can
+# still be edited.  This is rarely a good idea.
 
-#define NEXAD -31
-#define fshift pow(2.0,-1.0*(double)NEXAD)
-#define fscale (-xscale*xscale*fshift/mscale)
+case "$2,$3" in
+  merge,)
+    /usr/bin/perl -i.bak -ne 's/^/# /, s/^# #/#/ if /^Conflicts/ .. /#/; print' "$1" ;;
 
-/NPIPE 5;
-/NVMP 1;
+# ,|template,)
+#   /usr/bin/perl -i.bak -pe '
+#      print "\n" . `git diff --cached --name-status -r`
+#	 if /^#/ && $first++ == 0' "$1" ;;
 
-/JPSET xj[3], x[][], fix,      NPOS,xscale;
-/JPSET mj,    m[],   log,      NLOG,NMAN,mscale;
-/IPSET xi[3], x[][], fix,      NPOS,xscale;
-/IPSET ieps2, eps2,  log,      NLOG,NMAN,escale;
-/FOSET sx[3], a[][], fix,      NACC,fscale;
+  *) ;;
+esac
 
-pg_fix_addsub(SUB,xi,xj,xij,           NPOS,           D_FSU);
-pg_conv_ftol(xij,dx,                   NPOS,NLOG,NMAN, D_FTL);
-pg_log_shift(1,dx,x2,                  NLOG);
-
-pg_log_unsigned_add_itp(x2[0],x2[1], x2y2,   NLOG,NMAN,D_LAD,NCUT);
-pg_log_unsigned_add_itp(x2[2],ieps2, z2e2,   NLOG,NMAN,D_LAD,NCUT);
-pg_log_unsigned_add_itp(x2y2,z2e2,   r2,     NLOG,NMAN,D_LAD,NCUT);
-
-pg_log_shift(-1,r2,       r1,          NLOG);
-pg_log_muldiv(MUL,r2,r1,  r3,          NLOG,           D_LMU);
-pg_log_muldiv(SDIV,mj,r3,  mf,         NLOG,           D_LMU);
-pg_log_muldiv(MUL,mf,dx,  fx,          NLOG,           D_LMU);
-pg_log_expadd(fx,fxs,                  NEXAD,NLOG,NMAN, D_LMU);
-
-pg_conv_ltof(fxs,  ffx,                NLOG,NMAN,NFOR, D_LTF);
-pg_fix_accum(ffx,  sx,                 NFOR,NACC,      D_FAC);
+# SOB=$(git var GIT_AUTHOR_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
+# grep -qs "^$SOB" "$1" || echo "$SOB" >> "$1"
