One's philosophy is not best expressed in words; it is expressed in the choices one makes ... and the choice we make are ultimately our responsibility. -- Eleanor Roosevelt

diff --git a/a2452ae2924848aab3cc7cd74ad6dde1 b/a2452ae2924848aab3cc7cd74ad6dde1
--- a/a2452ae2924848aab3cc7cd74ad6dde1
+++ b/a2452ae2924848aab3cc7cd74ad6dde1
@@ -1,32 +1,25 @@
-Tue Mar  5 19:46:08 JST 2013
-/*
- * pfpga_info.c
- *
- * Copyright (C) 2006-2007 Tsuyoshi Hamada
- *                                All rights reserved.
- * 
- * No warranty is attached; 
- * I cannot take responsibility for errors or fitness for use.
- *
- */
+Sat Mar 16 19:47:11 JST 2013
+#!/bin/sh
+#
+# An example hook script to check the commit log message.
+# Called by "git commit" with one argument, the name of the file
+# that has the commit message.  The hook should exit with non-zero
+# status after issuing an appropriate message if it wants to stop the
+# commit.  The hook is allowed to edit the commit message file.
+#
+# To enable this hook, rename this file to "commit-msg".
 
-#include <stdio.h>
-#include <stdlib.h>
-#include <string.h>
+# Uncomment the below to add a Signed-off-by line to the message.
+# Doing this in a hook is a bad idea in general, but the prepare-commit-msg
+# hook is more suited to it.
+#
+# SOB=$(git var GIT_AUTHOR_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
+# grep -qs "^$SOB" "$1" || echo "$SOB" >> "$1"
 
-#define MAXBD 8
-#include "pg4.h"
+# This example catches duplicate Signed-off-by lines.
 
-int main(int argc, char* argv[])
-{
-  int devid=0;
-  char info[1024];
-
-  pg4_open(devid);
-  pg4_get_pfpga_info(devid, info);
-  pg4_close(devid);
-
-  printf("%s\n", info);
-
-  return 1;
+test "" = "$(grep '^Signed-off-by: ' "$1" |
+	 sort | uniq -c | sed -e '/^[ 	]*1[ 	]/d')" || {
+	echo >&2 Duplicate Signed-off-by lines.
+	exit 1
 }
