Happiness does not lie in happiness, but in the achievement of it. -- Fyodor Dostoyevsky

diff --git a/a27b43bf4a3248798913ede203c3f075 b/a27b43bf4a3248798913ede203c3f075
--- a/a27b43bf4a3248798913ede203c3f075
+++ b/a27b43bf4a3248798913ede203c3f075
@@ -1,134 +1,170 @@
-Sat Nov 21 19:30:39 JST 2015
-#include <stdio.h>
-#include <stdlib.h>
-#include <string.h>
-#include <time.h>
-#include <math.h>
-#include "pg_util.h"
+Mon Nov 23 20:02:58 JST 2015
+#!/bin/sh
+#
+# Copyright (c) 2006, 2008 Junio C Hamano
+#
+# The "pre-rebase" hook is run just before "git rebase" starts doing
+# its job, and can prevent the command from running by exiting with
+# non-zero status.
+#
+# The hook is called with the following parameters:
+#
+# $1 -- the upstream the series was forked from.
+# $2 -- the branch being rebased (or empty when rebasing the current branch).
+#
+# This sample shows how to prevent topic branches that are already
+# merged to 'next' branch from getting rebased, because allowing it
+# would result in rebasing already published history.
 
-#include "pgrapi.h"
+publish=next
+basebranch="$1"
+if test "$#" = 2
+then
+	topic="refs/heads/$2"
+else
+	topic=`git symbolic-ref HEAD` ||
+	exit 0 ;# we do not interrupt rebasing detached HEAD
+fi
 
-// #define DEBUG
+case "$topic" in
+refs/heads/??/*)
+	;;
+*)
+	exit 0 ;# we do not interrupt others.
+	;;
+esac
 
-#define   MAX(x,y)     (((x) > (y)) ?  (x) : (y))
-#define   MIN(x,y)     (((x) < (y)) ?  (x) : (y))
+# Now we are dealing with a topic branch being rebased
+# on top of master.  Is it OK to rebase it?
 
-#define NJMAX 16384
-
-#define NPIPE_PER_CHIP  1
-#define NCHIP_PER_BOARD 4
-
-#define NFLO 26
-#define NMAN 16
-#define RMODE 6
-
-static int      devid = 0;
-static int      __first = 0;
-
-static unsigned long long int fdata[NJMAX][FDIM];
-
-void
-force(double x[][3], double m[], double eps2, double a[][3], int n)
-{
-    double          log2(double);
-    int             i, j;
-    unsigned int    npipe, npipe_per_chip;
-    unsigned int    nchip;
-    unsigned int    jdata[JDIM];
-    if (__first == 0) {
-	b3open(devid);
-	pgr_reset(devid);
-	pgr_set_npipe_per_chip(devid, NPIPE_PER_CHIP);
-	pgr_set_jwidth(devid, 16);	// change manually 4 if grape
-	pgr_set_nchip(NCHIP_PER_BOARD);
-	__first = 1;
-    }
-
-    npipe_per_chip = NPIPE_PER_CHIP;
-    nchip = NCHIP_PER_BOARD;
-    npipe = nchip * npipe_per_chip;
-
-    for (j = 0; j < n; j++) {
-	unsigned int    xj[4];
-	xj[0] = (unsigned int) (double2pgpgfloat_r(x[j][0], 26, 16, 6));
-	xj[1] = (unsigned int) (double2pgpgfloat_r(x[j][1], 26, 16, 6));
-	xj[2] = (unsigned int) (double2pgpgfloat_r(x[j][2], 26, 16, 6));
-	xj[3] = (unsigned int) (double2pgpgfloat_r(m[j], 26, 16, 6));
-	for (i = 0; i < JDIM; i++)   jdata[i] = 0x0;
-	jdata[0] |= (0x3ffffff & xj[0]) << 0;	// mask(26)
-	jdata[0] |= (0x3f & xj[1]) << 26;	// mask(6)
-	jdata[1] |= (0xfffff & (xj[1] >> 6));	// mask(20)
-	jdata[1] |= (0xfff & xj[2]) << 20;	// mask(12)
-	jdata[2] |= (0x3fff & (xj[2] >> 12));	// mask(14)
-	jdata[2] |= (0x3ffff & xj[3]) << 14;	// mask(18)
-	jdata[3] |= (0xff & (xj[3] >> 18));	// mask(8)
-	pgr_setjpset_one(devid, j, jdata);
-    }
-
-    for (i = 0; i < n; i += npipe) {
-	int             nn, ii, ichip;
-	nn = MIN(npipe, n - i);
-
-#ifdef DEBUG
-	dum = e_time();
-#endif
-
-	for (ii = 0; ii < nn; ii += npipe_per_chip) {
-	    int             nnn, iii;
-	    ichip = ii / npipe_per_chip;
-
-	    nnn = MIN(npipe_per_chip, nn - ii);
-	    for (iii = 0; iii < nnn; iii++) {
-		unsigned int    idata[4];
-		idata[0] =
-		    (unsigned
-		     int) (double2pgpgfloat_r(x[i + ii + iii][0], 26, 16,
-					      6));
-		idata[1] =
-		    (unsigned
-		     int) (double2pgpgfloat_r(x[i + ii + iii][1], 26, 16,
-					      6));
-		idata[2] =
-		    (unsigned
-		     int) (double2pgpgfloat_r(x[i + ii + iii][2], 26, 16,
-					      6));
-		idata[3] =
-		    (unsigned int) (double2pgpgfloat_r(eps2, 26, 16, 6));
-		pgr_setipset_one(devid, ichip, iii, idata, 4);
-	    }
-	}
-#ifdef DEBUG
-	_t[2] += e_time() - dum;
-	dum = e_time();
-#endif
-
-	pgr_start_calc(devid, n);
-#ifdef DEBUG
-	_t[3] += e_time() - dum;
-	dum = e_time();
-#endif
-
-	pgr_getfoset(devid, fdata);
-	for (ii = 0; ii < nn; ii++) {
-	    a[i + ii][0] =
-		((double) ((long long int) fdata[ii][0] << 0)) *
-		((-1.0 / pow(2.0, (double) 31))) / pow(2.0, 0.0);
-	    a[i + ii][1] =
-		((double) ((long long int) fdata[ii][1] << 0)) *
-		((-1.0 / pow(2.0, (double) 31))) / pow(2.0, 0.0);
-	    a[i + ii][2] =
-		((double) ((long long int) fdata[ii][2] << 0)) *
-		((-1.0 / pow(2.0, (double) 31))) / pow(2.0, 0.0);
-	}
-#ifdef DEBUG
-	_t[4] += e_time() - dum;
-#endif
-
-    }
-#ifdef DEBUG
-    _t[0] = e_time() - _t[0];
-    fprintf(stderr, "total %g sec (jp %g, ip %g, c %g, fo %g %%)\n", _t[0],
-	    100.0 * _t[1] / _t[0], 100.0 * _t[2] / _t[0],
-	    100.0 * _t[3] / _t[0], 100.0 * _t[4] / _t[0]);
-#endif
+# Does the topic really exist?
+git show-ref -q "$topic" || {
+	echo >&2 "No such branch $topic"
+	exit 1
 }
+
+# Is topic fully merged to master?
+not_in_master=`git rev-list --pretty=oneline ^master "$topic"`
+if test -z "$not_in_master"
+then
+	echo >&2 "$topic is fully merged to master; better remove it."
+	exit 1 ;# we could allow it, but there is no point.
+fi
+
+# Is topic ever merged to next?  If so you should not be rebasing it.
+only_next_1=`git rev-list ^master "^$topic" ${publish} | sort`
+only_next_2=`git rev-list ^master           ${publish} | sort`
+if test "$only_next_1" = "$only_next_2"
+then
+	not_in_topic=`git rev-list "^$topic" master`
+	if test -z "$not_in_topic"
+	then
+		echo >&2 "$topic is already up-to-date with master"
+		exit 1 ;# we could allow it, but there is no point.
+	else
+		exit 0
+	fi
+else
+	not_in_next=`git rev-list --pretty=oneline ^${publish} "$topic"`
+	/usr/bin/perl -e '
+		my $topic = $ARGV[0];
+		my $msg = "* $topic has commits already merged to public branch:\n";
+		my (%not_in_next) = map {
+			/^([0-9a-f]+) /;
+			($1 => 1);
+		} split(/\n/, $ARGV[1]);
+		for my $elem (map {
+				/^([0-9a-f]+) (.*)$/;
+				[$1 => $2];
+			} split(/\n/, $ARGV[2])) {
+			if (!exists $not_in_next{$elem->[0]}) {
+				if ($msg) {
+					print STDERR $msg;
+					undef $msg;
+				}
+				print STDERR " $elem->[1]\n";
+			}
+		}
+	' "$topic" "$not_in_next" "$not_in_master"
+	exit 1
+fi
+
+exit 0
+
+################################################################
+
+This sample hook safeguards topic branches that have been
+published from being rewound.
+
+The workflow assumed here is:
+
+ * Once a topic branch forks from "master", "master" is never
+   merged into it again (either directly or indirectly).
+
+ * Once a topic branch is fully cooked and merged into "master",
+   it is deleted.  If you need to build on top of it to correct
+   earlier mistakes, a new topic branch is created by forking at
+   the tip of the "master".  This is not strictly necessary, but
+   it makes it easier to keep your history simple.
+
+ * Whenever you need to test or publish your changes to topic
+   branches, merge them into "next" branch.
+
+The script, being an example, hardcodes the publish branch name
+to be "next", but it is trivial to make it configurable via
+$GIT_DIR/config mechanism.
+
+With this workflow, you would want to know:
+
+(1) ... if a topic branch has ever been merged to "next".  Young
+    topic branches can have stupid mistakes you would rather
+    clean up before publishing, and things that have not been
+    merged into other branches can be easily rebased without
+    affecting other people.  But once it is published, you would
+    not want to rewind it.
+
+(2) ... if a topic branch has been fully merged to "master".
+    Then you can delete it.  More importantly, you should not
+    build on top of it -- other people may already want to
+    change things related to the topic as patches against your
+    "master", so if you need further changes, it is better to
+    fork the topic (perhaps with the same name) afresh from the
+    tip of "master".
+
+Let's look at this example:
+
+		   o---o---o---o---o---o---o---o---o---o "next"
+		  /       /           /           /
+		 /   a---a---b A     /           /
+		/   /               /           /
+	       /   /   c---c---c---c B         /
+	      /   /   /             \         /
+	     /   /   /   b---b C     \       /
+	    /   /   /   /             \     /
+    ---o---o---o---o---o---o---o---o---o---o---o "master"
+
+
+A, B and C are topic branches.
+
+ * A has one fix since it was merged up to "next".
+
+ * B has finished.  It has been fully merged up to "master" and "next",
+   and is ready to be deleted.
+
+ * C has not merged to "next" at all.
+
+We would want to allow C to be rebased, refuse A, and encourage
+B to be deleted.
+
+To compute (1):
+
+	git rev-list ^master ^topic next
+	git rev-list ^master        next
+
+	if these match, topic has not merged in next at all.
+
+To compute (2):
+
+	git rev-list master..topic
+
+	if this is empty, it is fully merged to "master".
