It's not the years in your life that count. It's the life in your years. -- Abraham Lincoln

diff --git a/b9c250f2774740e49c5b7bcd34ed9509 b/b9c250f2774740e49c5b7bcd34ed9509
--- a/b9c250f2774740e49c5b7bcd34ed9509
+++ b/b9c250f2774740e49c5b7bcd34ed9509
@@ -1,30 +1,25 @@
-Wed Mar  3 20:22:07 JST 2010
-library ieee;
-use ieee.std_logic_1164.all;
-use ieee.std_logic_arith.all;                                        
-use ieee.std_logic_unsigned.all;                                    
+Mon Mar 15 20:17:07 JST 2010
+#!/bin/sh
+#
+# An example hook script to check the commit log message.
+# Called by "git commit" with one argument, the name of the file
+# that has the commit message.  The hook should exit with non-zero
+# status after issuing an appropriate message if it wants to stop the
+# commit.  The hook is allowed to edit the commit message file.
+#
+# To enable this hook, rename this file to "commit-msg".
 
-entity setn is
-  port (
-    clk       : in std_logic;
-    we        : in std_logic;
-    idata     : in std_logic_vector(31 downto 0);
-    odata     : out std_logic_vector(31 downto 0));
-end setn;
+# Uncomment the below to add a Signed-off-by line to the message.
+# Doing this in a hook is a bad idea in general, but the prepare-commit-msg
+# hook is more suited to it.
+#
+# SOB=$(git var GIT_AUTHOR_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
+# grep -qs "^$SOB" "$1" || echo "$SOB" >> "$1"
 
-architecture rtl of setn is
-signal nreg :  std_logic_vector(31 downto 0) := "00000000000000000000000000000011"; -- default 3
-begin
+# This example catches duplicate Signed-off-by lines.
 
-odata <= nreg;
---odata <= "00000000000000000000000000000011";
-
-process (clk) begin
-  if(clk'event and clk='1') then
-    if(we = '1') then
-      nreg <= idata;
-    end if;
-  end if;
-end process;
-
-end rtl;
+test "" = "$(grep '^Signed-off-by: ' "$1" |
+	 sort | uniq -c | sed -e '/^[ 	]*1[ 	]/d')" || {
+	echo >&2 Duplicate Signed-off-by lines.
+	exit 1
+}
