If you would not be forgotten as soon as you are dead, either write things worth reading or do things worth writing. -- Benjamin Franklin

diff --git a/c1c05d16345c406091d1db05362cad48 b/c1c05d16345c406091d1db05362cad48
--- a/c1c05d16345c406091d1db05362cad48
+++ b/c1c05d16345c406091d1db05362cad48
@@ -1,115 +1,170 @@
-2021年  5月 15日 土曜日 11:24:01 JST
--- PGPG Floating-Point Compare
--- by Tsuyoshi Hamada (2004/10/01)
--- P: 1[O], 2[O], 
-library ieee;
-use ieee.std_logic_1164.all;
-use ieee.std_logic_unsigned.all;
-entity pg_float_compare_26_16_2 is
-  port( x : in std_logic_vector(25 downto 0);
-        y : in std_logic_vector(25 downto 0);
-        flag : out std_logic;           -- (x > y) ? 1 : 0
-        clk : in std_logic);
-end pg_float_compare_26_16_2;
-architecture rtl of pg_float_compare_26_16_2 is
+2021年  6月 13日 日曜日 11:25:08 JST
+#!/bin/sh
+#
+# Copyright (c) 2006, 2008 Junio C Hamano
+#
+# The "pre-rebase" hook is run just before "git rebase" starts doing
+# its job, and can prevent the command from running by exiting with
+# non-zero status.
+#
+# The hook is called with the following parameters:
+#
+# $1 -- the upstream the series was forked from.
+# $2 -- the branch being rebased (or empty when rebasing the current branch).
+#
+# This sample shows how to prevent topic branches that are already
+# merged to 'next' branch from getting rebased, because allowing it
+# would result in rebasing already published history.
 
--- ----------------------------------------------------------------------------
-signal signx, signy, nonzx, nonzy :  std_logic;
-signal expx,expy : std_logic_vector(7 downto 0);      -- nbit_exp-1
-signal manx,many : std_logic_vector(15 downto 0);     -- nbit_man-1
--- ----------------------------------------------------------------------------
-signal sx0,sx1,sy0,sy1 : std_logic;
-signal nx0,nx1,ny0,ny1 : std_logic;
-signal expx0,expy0 : std_logic_vector(7 downto 0); -- nbit_exp-1
-signal manx0,many0 : std_logic_vector(15 downto 0); -- nbit_man-1
-signal exp_x,exp_y,exy0,eyx0 : std_logic_vector(8 downto 0); -- nbit_exp
-signal exgey0,exgey1,eygex0,eygex1 : std_logic;
-signal mx,my,mxy,myx : std_logic_vector(16 downto 0);   -- nbit_man
-signal mxgey0,mygex0,mygex1 : std_logic;
-signal exeqy : std_logic;
-signal flag0,flag1 : std_logic;
-signal nygex : std_logic;
-signal nontobi0 : std_logic;
-signal is_xeqy0,mxeqy,mxgey1 : std_logic;
-signal b : std_logic_vector(9 downto 0);
-begin
-                             --2.0,  4.0, 0.5, 0.0, 1024.0
-  signx <= x(25);            -- 0 ,  0  ,  0 , *,   0,
-  nonzx <= x(24);            -- 1 ,  1  ,  1 , 0,   1,
-  expx <= x(23 downto 16);   -- 1 ,  2  , -1 , *   10,
-  manx <= x(15 downto 0);    -- 0 ,  0  ,  0 , *,   0,
+publish=next
+basebranch="$1"
+if test "$#" = 2
+then
+	topic="refs/heads/$2"
+else
+	topic=`git symbolic-ref HEAD` ||
+	exit 0 ;# we do not interrupt rebasing detached HEAD
+fi
 
-  signy <= y(25);
-  nonzy <= y(24);
-  expy <= y(23 downto 16);
-  many <= y(15 downto 0);
+case "$topic" in
+refs/heads/??/*)
+	;;
+*)
+	exit 0 ;# we do not interrupt others.
+	;;
+esac
 
-  -- buffering
-  sx0  <= signx;
-  sy0  <= signy;
-  nx0  <= nonzx;
-  ny0  <= nonzy;
-  expx0 <= expx;
-  expy0 <= expy;
-  manx0 <= manx;
-  many0 <= many;
+# Now we are dealing with a topic branch being rebased
+# on top of master.  Is it OK to rebase it?
 
-  -- biassing to unsigned
-  exp_x(8) <= '0';                         -- nbit_exp
-  exp_x(7) <= not expx0(7);               -- nbit_exp-1, nbit_exp-1
-  exp_x(6 downto 0) <= expx0(6 downto 0); -- nbit_exp-2, nbit_exp-2
-  exp_y(8) <= '0';                         -- nbit_exp
-  exp_y(7) <= not expy0(7);               -- nbit_exp-1, nbit_exp-1
-  exp_y(6 downto 0) <= expy0(6 downto 0); -- nbit_exp-2, nbit_exp-2
+# Does the topic really exist?
+git show-ref -q "$topic" || {
+	echo >&2 "No such branch $topic"
+	exit 1
+}
 
-  -- sub exponent
-  exy0 <= exp_x - exp_y;
-  eyx0 <= exp_y - exp_x;
-  eygex0 <= exy0(8);
-  exgey0 <= eyx0(8);
+# Is topic fully merged to master?
+not_in_master=`git rev-list --pretty=oneline ^master "$topic"`
+if test -z "$not_in_master"
+then
+	echo >&2 "$topic is fully merged to master; better remove it."
+	exit 1 ;# we could allow it, but there is no point.
+fi
 
-  -- compare mantissa
-  mx <= '0' & manx0;
-  my <= '0' & many0;
-  mxy <= mx - my;
-  myx <= my - mx;
-  mxgey0 <= myx(16);   -- nbit_man
-  mygex0 <= mxy(16);   -- nbit_man
+# Is topic ever merged to next?  If so you should not be rebasing it.
+only_next_1=`git rev-list ^master "^$topic" ${publish} | sort`
+only_next_2=`git rev-list ^master           ${publish} | sort`
+if test "$only_next_1" = "$only_next_2"
+then
+	not_in_topic=`git rev-list "^$topic" master`
+	if test -z "$not_in_topic"
+	then
+		echo >&2 "$topic is already up-to-date with master"
+		exit 1 ;# we could allow it, but there is no point.
+	else
+		exit 0
+	fi
+else
+	not_in_next=`git rev-list --pretty=oneline ^${publish} "$topic"`
+	/usr/bin/perl -e '
+		my $topic = $ARGV[0];
+		my $msg = "* $topic has commits already merged to public branch:\n";
+		my (%not_in_next) = map {
+			/^([0-9a-f]+) /;
+			($1 => 1);
+		} split(/\n/, $ARGV[1]);
+		for my $elem (map {
+				/^([0-9a-f]+) (.*)$/;
+				[$1 => $2];
+			} split(/\n/, $ARGV[2])) {
+			if (!exists $not_in_next{$elem->[0]}) {
+				if ($msg) {
+					print STDERR $msg;
+					undef $msg;
+				}
+				print STDERR " $elem->[1]\n";
+			}
+		}
+	' "$topic" "$not_in_next" "$not_in_master"
+	exit 1
+fi
 
-  -- PIPELINE 1 ----------------------------------------------------------------
-  process(clk) begin
-    if(clk'event and clk='1') then
-      sx1  <= sx0;
-      sy1  <= sy0;
-      nx1  <= nx0;
-      ny1  <= ny0;
-      exgey1 <= exgey0;
-      eygex1 <= eygex0;
-      mygex1 <= mygex0;
-      mxgey1 <= mxgey0;
-    end if;
-  end process;
+exit 0
 
-  exeqy <= exgey1 nor eygex1;
-  mxeqy <= not (mygex1 or mxgey1);  
+################################################################
 
-  -- bawai wake vector
-  b <= nx1 & ny1 & sx1 & sy1 & exeqy & exgey1 & eygex1 & mxeqy & mxgey1 & mygex1;
+This sample hook safeguards topic branches that have been
+published from being rewound.
 
-  flag0 <= 
-    ((not b(9)) and b(8) and b(6)         ) or                                                       -- "01X1XXXXXX", -- x = 0, y < 0
-    (b(9) and (not b(8)) and (not b(7))   ) or                                                       -- "100XXXXXXX", -- x > 0, y = 0
-    (b(9) and b(8) and (not b(7)) and b(6)) or                                                       -- "1101XXXXXX", -- x > 0, y < 0
-    (b(9) and b(8) and (not b(7)) and (not b(6)) and (not b(5)) and b(4) and (not b(3))) or          -- "1100010XXX", -- x > y > 0
-    (b(9) and b(8) and (not b(7)) and (not b(6)) and b(5) and (not b(2)) and b(1) and (not b(0))) or -- "11001XX010", -- x > y > 0
-    (b(9) and b(8) and b(7) and b(6) and (not b(5)) and (not b(4)) and b(3)) or                      -- "1111001XXX", -- 0 > x > y
-    (b(9) and b(8) and b(7) and b(6) and b(5) and (not b(2)) and (not b(1)) and b(0));               -- "11111XX001", -- 0 > x > y
+The workflow assumed here is:
 
-  -- PIPELINE 2 ----------------------------------------------------------------
-  process(clk) begin
-    if(clk'event and clk='1') then
-      flag <= flag0;
-    end if;
-  end process;
+ * Once a topic branch forks from "master", "master" is never
+   merged into it again (either directly or indirectly).
 
-end rtl;
+ * Once a topic branch is fully cooked and merged into "master",
+   it is deleted.  If you need to build on top of it to correct
+   earlier mistakes, a new topic branch is created by forking at
+   the tip of the "master".  This is not strictly necessary, but
+   it makes it easier to keep your history simple.
+
+ * Whenever you need to test or publish your changes to topic
+   branches, merge them into "next" branch.
+
+The script, being an example, hardcodes the publish branch name
+to be "next", but it is trivial to make it configurable via
+$GIT_DIR/config mechanism.
+
+With this workflow, you would want to know:
+
+(1) ... if a topic branch has ever been merged to "next".  Young
+    topic branches can have stupid mistakes you would rather
+    clean up before publishing, and things that have not been
+    merged into other branches can be easily rebased without
+    affecting other people.  But once it is published, you would
+    not want to rewind it.
+
+(2) ... if a topic branch has been fully merged to "master".
+    Then you can delete it.  More importantly, you should not
+    build on top of it -- other people may already want to
+    change things related to the topic as patches against your
+    "master", so if you need further changes, it is better to
+    fork the topic (perhaps with the same name) afresh from the
+    tip of "master".
+
+Let's look at this example:
+
+		   o---o---o---o---o---o---o---o---o---o "next"
+		  /       /           /           /
+		 /   a---a---b A     /           /
+		/   /               /           /
+	       /   /   c---c---c---c B         /
+	      /   /   /             \         /
+	     /   /   /   b---b C     \       /
+	    /   /   /   /             \     /
+    ---o---o---o---o---o---o---o---o---o---o---o "master"
+
+
+A, B and C are topic branches.
+
+ * A has one fix since it was merged up to "next".
+
+ * B has finished.  It has been fully merged up to "master" and "next",
+   and is ready to be deleted.
+
+ * C has not merged to "next" at all.
+
+We would want to allow C to be rebased, refuse A, and encourage
+B to be deleted.
+
+To compute (1):
+
+	git rev-list ^master ^topic next
+	git rev-list ^master        next
+
+	if these match, topic has not merged in next at all.
+
+To compute (2):
+
+	git rev-list master..topic
+
+	if this is empty, it is fully merged to "master".
