I always looked ahead. -- Chris Evert

diff --git a/e14eeed4f11a40b381fd12a779e65b43 b/e14eeed4f11a40b381fd12a779e65b43
--- a/e14eeed4f11a40b381fd12a779e65b43
+++ b/e14eeed4f11a40b381fd12a779e65b43
@@ -1,15 +1,25 @@
-2020年 12月  9日 水曜日 10:37:03 JST
+2020年 12月 21日 月曜日 09:28:51 JST
 #!/bin/sh
 #
-# An example hook script to verify what is about to be committed
-# by applypatch from an e-mail message.
+# An example hook script to check the commit log message.
+# Called by "git commit" with one argument, the name of the file
+# that has the commit message.  The hook should exit with non-zero
+# status after issuing an appropriate message if it wants to stop the
+# commit.  The hook is allowed to edit the commit message file.
 #
-# The hook should exit with non-zero status after issuing an
-# appropriate message if it wants to stop the commit.
-#
-# To enable this hook, rename this file to "pre-applypatch".
+# To enable this hook, rename this file to "commit-msg".
 
-. git-sh-setup
-test -x "$GIT_DIR/hooks/pre-commit" &&
-	exec "$GIT_DIR/hooks/pre-commit" ${1+"$@"}
-:
+# Uncomment the below to add a Signed-off-by line to the message.
+# Doing this in a hook is a bad idea in general, but the prepare-commit-msg
+# hook is more suited to it.
+#
+# SOB=$(git var GIT_AUTHOR_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
+# grep -qs "^$SOB" "$1" || echo "$SOB" >> "$1"
+
+# This example catches duplicate Signed-off-by lines.
+
+test "" = "$(grep '^Signed-off-by: ' "$1" |
+	 sort | uniq -c | sed -e '/^[ 	]*1[ 	]/d')" || {
+	echo >&2 Duplicate Signed-off-by lines.
+	exit 1
+}
