You are going to let the fear of poverty govern your life and your reward will be that you will eat, but you will not live. -- George Bernard Shaw

diff --git a/e76a039d68ba408f95a2f3d330668a4c b/e76a039d68ba408f95a2f3d330668a4c
--- a/e76a039d68ba408f95a2f3d330668a4c
+++ b/e76a039d68ba408f95a2f3d330668a4c
@@ -1,15 +1,25 @@
-2021年  1月 20日 水曜日 10:55:08 JST
-#!/usr/bin/env python3
-import cv2
-import glob
-from datetime import datetime
-import time 
+2021年  1月 24日 日曜日 09:55:01 JST
+#!/bin/sh
+#
+# An example hook script to check the commit log message.
+# Called by "git commit" with one argument, the name of the file
+# that has the commit message.  The hook should exit with non-zero
+# status after issuing an appropriate message if it wants to stop the
+# commit.  The hook is allowed to edit the commit message file.
+#
+# To enable this hook, rename this file to "commit-msg".
 
-while(True):
-    tnow = datetime.now().strftime('%Y%m%d_%H_%M_%S_%f')
-    print(tnow)
+# Uncomment the below to add a Signed-off-by line to the message.
+# Doing this in a hook is a bad idea in general, but the prepare-commit-msg
+# hook is more suited to it.
+#
+# SOB=$(git var GIT_AUTHOR_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
+# grep -qs "^$SOB" "$1" || echo "$SOB" >> "$1"
 
-    with open(".tc~", "w") as file:
-        file.write(tnow +"\n")
+# This example catches duplicate Signed-off-by lines.
 
-    time.sleep(3)
+test "" = "$(grep '^Signed-off-by: ' "$1" |
+	 sort | uniq -c | sed -e '/^[ 	]*1[ 	]/d')" || {
+	echo >&2 Duplicate Signed-off-by lines.
+	exit 1
+}
