The most important thing is to enjoy your life - to be happy - It's all that matters. -- Audrey Hepbarn

diff --git a/eb2cc0e17c224d7cb3a3b91048ada2f6 b/eb2cc0e17c224d7cb3a3b91048ada2f6
--- a/eb2cc0e17c224d7cb3a3b91048ada2f6
+++ b/eb2cc0e17c224d7cb3a3b91048ada2f6
@@ -1,91 +1,51 @@
-Fri May  9 20:23:14 JST 2008
--- Copyright 2004-2005 Tsuyoshi Hamada
---clk         __~~ __~~ __~~ __~~ __~~ __~~ __~~ __~~ __~~ __~~ __~~ __~~ __~~ __~~ __
---MEM_WEHA         _______/~~~~\__________
---MEM_WELA    _______/~~~~\__________
---MEM_DTIA[L]        < L  >              
---MEM_DTIA[H]             < H  >              
---wait             _______/~~~~~~~~~\__________
---dtl
+Mon May 12 20:08:22 JST 2008
+#!/bin/sh
+#
+# An example hook script to verify what is about to be committed.
+# Called by "git commit" with no arguments.  The hook should
+# exit with non-zero status after issuing an appropriate message if
+# it wants to stop the commit.
+#
+# To enable this hook, rename this file to "pre-commit".
 
-library IEEE;
-use IEEE.STD_LOGIC_1164.ALL;
-use IEEE.STD_LOGIC_UNSIGNED.ALL;
-use IEEE.STD_LOGIC_ARITH.ALL;
+if git rev-parse --verify HEAD >/dev/null 2>&1
+then
+	against=HEAD
+else
+	# Initial commit: diff against an empty tree object
+	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
+fi
 
+# If you want to allow non-ascii filenames set this variable to true.
+allownonascii=$(git config hooks.allownonascii)
 
-entity FIFOFIFO is
-  port (
-    -- pcicnt input
-    MEM_ADA  : in std_logic_vector(19 downto 0);     -- DPRAM Port B R/W Address
-    MEM_WEHA : in std_logic;
-    MEM_WELA : in std_logic;
-    MEM_DTIA : in std_logic_vector(63 downto 0);
-    -- output
-    MEM_AD     : out std_logic_vector(31 downto 0);
-    MEM_WE     : out std_logic;
-    MEM_DTI    : out std_logic_vector(63 downto 0);
+# Redirect output to stderr.
+exec 1>&2
 
-    RST : in  std_logic;
-    CLK : in  std_logic
-    );
-end FIFOFIFO;
+# Cross platform projects tend to avoid non-ascii filenames; prevent
+# them from being added to the repository. We exploit the fact that the
+# printable range starts at the space character and ends with tilde.
+if [ "$allownonascii" != "true" ] &&
+	# Note that the use of brackets around a tr range is ok here, (it's
+	# even required, for portability to Solaris 10's /usr/bin/tr), since
+	# the square bracket bytes happen to fall in the designated range.
+	test $(git diff --cached --name-only --diff-filter=A -z $against |
+	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
+then
+	echo "Error: Attempt to add a non-ascii file name."
+	echo
+	echo "This can cause problems if you want to work"
+	echo "with people on other platforms."
+	echo
+	echo "To be portable it is advisable to rename the file ..."
+	echo
+	echo "If you know what you are doing you can disable this"
+	echo "check using:"
+	echo
+	echo "  git config hooks.allownonascii true"
+	echo
+	exit 1
+fi
 
-architecture rtl of FIFOFIFO is
-  signal we   : std_logic :='0'; 
-  signal adr  : std_logic_vector(19 downto 0) := (others=>'0'); 
-  signal data : std_logic_vector(63 downto 0) := (others=>'0'); 
-begin
-
-  MEM_AD(31 downto 20) <= (others=>'0');
-  MEM_AD(19 downto 0) <= adr;
-
-  MEM_WE <= we;
-  MEM_DTI <= data;
-
-
-  process (RST,CLK,MEM_WEHA,MEM_WELA) begin
-    if(RST='1') then
-      adr <= (others=>'0');
-    elsif (CLK'event and CLK='1') then
-      if(MEM_WEHA='1' AND MEM_WELA='1') then
-        adr <= MEM_ADA(19 downto 0);
-      elsif(MEM_WEHA='0' AND MEM_WELA='1') then
-        adr <= MEM_ADA(19 downto 0);
-      elsif(MEM_WEHA='1' AND MEM_WELA='0') then
-        adr <= MEM_ADA(19 downto 0);
-      end if;
-    end if;
-  end process;
-
-  process (RST,CLK,MEM_WEHA,MEM_WELA) begin
-    if(RST='1') then
-      we <= '0';
-    elsif (CLK'event and CLK='1') then
-      if(MEM_WEHA='1' AND MEM_WELA='1') then
-        we <= '1';
-      elsif(MEM_WEHA='0' AND MEM_WELA='1') then
-        we <= '0';
-      elsif(MEM_WEHA='1' AND MEM_WELA='0') then
-        we <= '1';
-      else
-        we <= '0';
-      end if;
-    end if;
-  end process;
-
-  process (RST,CLK,MEM_WEHA,MEM_WELA) begin
-    if(RST='1') then
-      data <= (others=>'0');
-    elsif (CLK'event and CLK='1') then
-      if(MEM_WEHA='1' AND MEM_WELA='1') then
-        data <= MEM_DTIA;
-      elsif(MEM_WEHA='0' AND MEM_WELA='1') then
-        data(31 downto 0) <= MEM_DTIA(31 downto 0);
-      elsif(MEM_WEHA='1' AND MEM_WELA='0') then
-        data(63 downto 32) <= MEM_DTIA(63 downto 32);
-      end if;
-    end if;
-  end process;
-
-end rtl;
+# If there are whitespace errors, print the offending file names and fail.
+exec git diff-index --check --cached $against --
