I have nothing to offer but blood, toil, tears, and sweat. -- Winston Churchill

diff --git a/efd94bba10f3439581ff799895d38d23 b/efd94bba10f3439581ff799895d38d23
--- a/efd94bba10f3439581ff799895d38d23
+++ b/efd94bba10f3439581ff799895d38d23
@@ -1,214 +1,170 @@
-2023Âπ¥  1Êúà  9Êó• ÊúàÊõúÊó• 09:36:24 JST
--- 1: cfg_en0 set(clock start): 0x0f1
--- 2: cfg_prog_b0 down        : 0x0e1
--- 3: cfg_prog_b0 up          : 0x0f1
--- 4: set data
--- 5: config start (is_dsend) : 0x1f1
--- 6: end config(cfg_en0 down): 0x0f0
-library ieee;
-use ieee.std_logic_1164.all;
-use ieee.std_logic_arith.all;
-use ieee.std_logic_unsigned.all;
+2023Âπ¥  1Êúà 10Êó• ÁÅ´ÊõúÊó• 10:31:37 JST
+#!/bin/sh
+#
+# Copyright (c) 2006, 2008 Junio C Hamano
+#
+# The "pre-rebase" hook is run just before "git rebase" starts doing
+# its job, and can prevent the command from running by exiting with
+# non-zero status.
+#
+# The hook is called with the following parameters:
+#
+# $1 -- the upstream the series was forked from.
+# $2 -- the branch being rebased (or empty when rebasing the current branch).
+#
+# This sample shows how to prevent topic branches that are already
+# merged to 'next' branch from getting rebased, because allowing it
+# would result in rebasing already published history.
 
-entity pfpga_config is
-  port( clk   : in std_logic;
-        rst_n : in std_logic;
-        cmd_reg  : in std_logic_vector(8 downto 0);
-        data_reg : in std_logic_vector(31 downto 0);
-	-- Pipeline FPGA side
-        CFG_D         : out  std_logic_vector(7 downto 0);  -- DATA
-        CFG_CCLK      : out  std_logic;           -- CCLK
-        CFG_PROG_B0   : out  std_logic;           -- DDR-FPGA0å¸ÇØPROG_B
-        CFG_PROG_B1   : out  std_logic;           -- DDR-FPGA1å¸ÇØPROG_B
-        CFG_PROG_B2   : out  std_logic;           -- DDR-FPGA2å¸ÇØPROG_B
-        CFG_PROG_B3   : out  std_logic;           -- DDR-FPGA3å¸ÇØPROG_B
-        CFG_CS_B0     : out  std_logic;           -- DDR-FPGA0å¸ÇØCS_B
-        CFG_CS_B1     : out  std_logic;           -- DDR-FPGA1å¸ÇØCS_B
-        CFG_CS_B2     : out  std_logic;           -- DDR-FPGA2å¸ÇØCS_B
-        CFG_CS_B3     : out  std_logic;           -- DDR-FPGA3å¸ÇØCS_B
-        CFG_RDWR_B    : out  std_logic);          -- RD/WR_B
-end pfpga_config;
+publish=next
+basebranch="$1"
+if test "$#" = 2
+then
+	topic="refs/heads/$2"
+else
+	topic=`git symbolic-ref HEAD` ||
+	exit 0 ;# we do not interrupt rebasing detached HEAD
+fi
 
-architecture rtl of pfpga_config is
-signal cclk_cnt   : std_logic_vector(1 downto 0);
-signal cfg_cnt    : std_logic_vector(3 downto 0) := "1111";
-signal cfg_en     : std_logic_vector(3 downto 0);
-signal cfg_prog_b : std_logic_vector(3 downto 0);
-signal dbuf0,dbuf1,dbuf2,dbuf3 : std_logic_vector(7 downto 0);
-signal is_cclk : std_logic;
-signal cs : std_logic;
-signal stop_cnt : std_logic := '1';
-signal rund : std_logic_vector(10 downto 0);
-signal cfg_d_port  : std_logic_vector(7 downto 0);
-signal is_dsend : std_logic;
-signal cfg_start0,cfg_start1 : std_logic;
-begin
+case "$topic" in
+refs/heads/??/*)
+	;;
+*)
+	exit 0 ;# we do not interrupt others.
+	;;
+esac
 
-  CFG_RDWR_B <= '0';
-  cfg_en     <= cmd_reg(3 downto 0);
-  cfg_prog_b <= cmd_reg(7 downto 4);
-  cfg_start0 <= cmd_reg(8);
+# Now we are dealing with a topic branch being rebased
+# on top of master.  Is it OK to rebase it?
 
-  process(clk) begin
-    if(clk'event and clk='1') then
-      cfg_start1 <= cfg_start0;
-    end if;
-  end process;
+# Does the topic really exist?
+git show-ref -q "$topic" || {
+	echo >&2 "No such branch $topic"
+	exit 1
+}
 
-  process(clk,rst_n) begin
-    if(rst_n = '0') then
-      is_dsend <= '0';
-    elsif(clk'event and clk='1') then
-      if((cfg_start0 = '1') and (cfg_start1 = '0')) then
-        is_dsend <='1';
-      else
-        is_dsend <='0';
-      end if;
-    end if;
-  end process;
+# Is topic fully merged to master?
+not_in_master=`git rev-list --pretty=oneline ^master "$topic"`
+if test -z "$not_in_master"
+then
+	echo >&2 "$topic is fully merged to master; better remove it."
+	exit 1 ;# we could allow it, but there is no point.
+fi
 
+# Is topic ever merged to next?  If so you should not be rebasing it.
+only_next_1=`git rev-list ^master "^$topic" ${publish} | sort`
+only_next_2=`git rev-list ^master           ${publish} | sort`
+if test "$only_next_1" = "$only_next_2"
+then
+	not_in_topic=`git rev-list "^$topic" master`
+	if test -z "$not_in_topic"
+	then
+		echo >&2 "$topic is already up-to-date with master"
+		exit 1 ;# we could allow it, but there is no point.
+	else
+		exit 0
+	fi
+else
+	not_in_next=`git rev-list --pretty=oneline ^${publish} "$topic"`
+	/usr/bin/perl -e '
+		my $topic = $ARGV[0];
+		my $msg = "* $topic has commits already merged to public branch:\n";
+		my (%not_in_next) = map {
+			/^([0-9a-f]+) /;
+			($1 => 1);
+		} split(/\n/, $ARGV[1]);
+		for my $elem (map {
+				/^([0-9a-f]+) (.*)$/;
+				[$1 => $2];
+			} split(/\n/, $ARGV[2])) {
+			if (!exists $not_in_next{$elem->[0]}) {
+				if ($msg) {
+					print STDERR $msg;
+					undef $msg;
+				}
+				print STDERR " $elem->[1]\n";
+			}
+		}
+	' "$topic" "$not_in_next" "$not_in_master"
+	exit 1
+fi
 
--- stop_cnt ,cs -------------------------------------
-  process(clk) begin
-    if(clk'event and clk='1') then
-      rund(10) <= rund(9);
-      rund(9) <= rund(8);
-      rund(8) <= rund(7);
-      rund(7) <= rund(6);
-      rund(6) <= rund(5);
-      rund(5) <= rund(4);
-      rund(4) <= rund(3);
-      rund(3) <= rund(2);
-      rund(2) <= rund(1);
-      rund(1) <= rund(0);
-      rund(0) <= is_dsend;
-    end if;
-  end process;
+exit 0
 
-  process(clk) begin
-    if(clk'event and clk='1') then
-      if((rund(7) = '0') AND (rund(6) = '1')) then
-        stop_cnt <='1';
-      elsif((is_dsend='1') AND (rund(0) = '0')) then
-        stop_cnt <='0';
-      end if;
-    end if;
-  end process;
+################################################################
 
-  process(clk,rst_n) begin
-    if(rst_n = '0') then
-      cs <= '0';
-    elsif(clk'event and clk='1') then
-      if((rund(0)='1') AND (rund(1) = '0')) then
-        cs <= '1';
-      elsif((rund(9) = '0') AND (rund(8) = '1')) then
-        cs <= '0';
-      end if; 
-    end if;
-  end process;
--------------------------------------
+This sample hook safeguards topic branches that have been
+published from being rewound.
 
--- CFG_D, CFG_CS_B<n> output ----------
-  process(clk,cclk_cnt(0)) begin
-    if(cclk_cnt(0)='1') then
-      CFG_D <= cfg_d_port;
-      CFG_CS_B0 <= NOT (cs AND cfg_en(0));
-      CFG_CS_B1 <= NOT (cs AND cfg_en(1));
-      CFG_CS_B2 <= NOT (cs AND cfg_en(2));
-      CFG_CS_B3 <= NOT (cs AND cfg_en(3));
-    elsif(clk'event and clk='1') then
-      CFG_D <= cfg_d_port;
-      CFG_CS_B0 <= NOT (cs AND cfg_en(0));
-      CFG_CS_B1 <= NOT (cs AND cfg_en(1));
-      CFG_CS_B2 <= NOT (cs AND cfg_en(2));
-      CFG_CS_B3 <= NOT (cs AND cfg_en(3));
-    end if;
-  end process;
--------------------------------------
+The workflow assumed here is:
 
+ * Once a topic branch forks from "master", "master" is never
+   merged into it again (either directly or indirectly).
 
--- SEND_CFG_DATA --------------------
+ * Once a topic branch is fully cooked and merged into "master",
+   it is deleted.  If you need to build on top of it to correct
+   earlier mistakes, a new topic branch is created by forking at
+   the tip of the "master".  This is not strictly necessary, but
+   it makes it easier to keep your history simple.
 
-  dbuf3(7 downto 0) <= data_reg(0)&data_reg(1)&data_reg(2)&data_reg(3)&data_reg(4)&data_reg(5)&data_reg(6)&data_reg(7);
-  dbuf2(7 downto 0) <= data_reg(8)&data_reg(9)&data_reg(10)&data_reg(11)&data_reg(12)&data_reg(13)&data_reg(14)&data_reg(15);
-  dbuf1(7 downto 0) <= data_reg(16)&data_reg(17)&data_reg(18)&data_reg(19)&data_reg(20)&data_reg(21)&data_reg(22)&data_reg(23);
-  dbuf0(7 downto 0) <= data_reg(24)&data_reg(25)&data_reg(26)&data_reg(27)&data_reg(28)&data_reg(29)&data_reg(30)&data_reg(31);
+ * Whenever you need to test or publish your changes to topic
+   branches, merge them into "next" branch.
 
+The script, being an example, hardcodes the publish branch name
+to be "next", but it is trivial to make it configurable via
+$GIT_DIR/config mechanism.
 
-  process(clk) begin
-    if((is_dsend = '1')AND(rund(0)='0')) then
-      cfg_d_port <= "00000000";
-    elsif(clk'event and clk='1') then
-      case cfg_cnt is
-      when "0000" =>
-        cfg_d_port <= dbuf0;
-      when "0001" =>
-        cfg_d_port <= dbuf0;
-      when "0010" =>
-        cfg_d_port <= dbuf1;
-      when "0011" =>
-        cfg_d_port <= dbuf1;
-      when "0100" =>
-        cfg_d_port <= dbuf2;
-      when "0101" =>
-        cfg_d_port <= dbuf2;
-      when "0110" =>
-        cfg_d_port <= dbuf3;
-      when "0111" =>
-        cfg_d_port <= dbuf3;
-      when others =>
-        cfg_d_port <= "00000000";
-      end case;
-    end if;
-  end process;
+With this workflow, you would want to know:
 
-  process(clk,stop_cnt) begin
-    if(clk'event and clk='1') then
-      if(stop_cnt='1')then
-        cfg_cnt <= "0000";
-      else
-        cfg_cnt <= cfg_cnt + "0001";
-      end if;
-    end if;
-  end process;
+(1) ... if a topic branch has ever been merged to "next".  Young
+    topic branches can have stupid mistakes you would rather
+    clean up before publishing, and things that have not been
+    merged into other branches can be easily rebased without
+    affecting other people.  But once it is published, you would
+    not want to rewind it.
+
+(2) ... if a topic branch has been fully merged to "master".
+    Then you can delete it.  More importantly, you should not
+    build on top of it -- other people may already want to
+    change things related to the topic as patches against your
+    "master", so if you need further changes, it is better to
+    fork the topic (perhaps with the same name) afresh from the
+    tip of "master".
+
+Let's look at this example:
+
+		   o---o---o---o---o---o---o---o---o---o "next"
+		  /       /           /           /
+		 /   a---a---b A     /           /
+		/   /               /           /
+	       /   /   c---c---c---c B         /
+	      /   /   /             \         /
+	     /   /   /   b---b C     \       /
+	    /   /   /   /             \     /
+    ---o---o---o---o---o---o---o---o---o---o---o "master"
 
 
--------------------------------------
+A, B and C are topic branches.
 
+ * A has one fix since it was merged up to "next".
 
--- CFG_PROG_B<n> -------------------- 
-  process(clk) begin
-    if(clk'event and clk='1') then
-      if(rst_n = '0') then
-        CFG_PROG_B0 <=  '1';
-        CFG_PROG_B1 <=  '1';
-        CFG_PROG_B2 <=  '1';
-        CFG_PROG_B3 <=  '1';
-      else
-        CFG_PROG_B0 <=  cfg_prog_b(0);
-        CFG_PROG_B1 <=  cfg_prog_b(1);
-        CFG_PROG_B2 <=  cfg_prog_b(2);
-        CFG_PROG_B3 <=  cfg_prog_b(3);
-      end if;
-    end if;
-  end process;
--------------------------------------
+ * B has finished.  It has been fully merged up to "master" and "next",
+   and is ready to be deleted.
 
--- Generate CFG_CCLK ----------------
-  CFG_CCLK <= not cclk_cnt(0);
-  is_cclk <= cfg_en(0) OR cfg_en(1) OR cfg_en(2) OR cfg_en(3);
+ * C has not merged to "next" at all.
 
-  process(clk) 
-  begin
-    if(clk'event and clk='1') then
-      if(is_cclk='0') then
-        cclk_cnt <= "00";
-      else
-        cclk_cnt <= cclk_cnt + "01";
-      end if;
-    end if;
-  end process;
--------------------------------------
+We would want to allow C to be rebased, refuse A, and encourage
+B to be deleted.
 
+To compute (1):
 
-end rtl;
+	git rev-list ^master ^topic next
+	git rev-list ^master        next
+
+	if these match, topic has not merged in next at all.
+
+To compute (2):
+
+	git rev-list master..topic
+
+	if this is empty, it is fully merged to "master".
