Life isn't about finding yourself. Life is about creating yourself. -- George Bernard Shaw

diff --git a/f132df5765304a18bb8bd3ce8f320a9f b/f132df5765304a18bb8bd3ce8f320a9f
--- a/f132df5765304a18bb8bd3ce8f320a9f
+++ b/f132df5765304a18bb8bd3ce8f320a9f
@@ -1,48 +1,37 @@
-2020年 10月 11日 日曜日 11:48:48 JST
-#!/usr/bin/env python3
-# -*- coding: utf-8 -*-
-import numpy as np
-import cv2
+2020年 10月 12日 月曜日 09:40:10 JST
+#!/bin/sh
+#
+# An example hook script to prepare the commit log message.
+# Called by "git commit" with the name of the file that has the
+# commit message, followed by the description of the commit
+# message's source.  The hook's purpose is to edit the commit
+# message file.  If the hook fails with a non-zero status,
+# the commit is aborted.
+#
+# To enable this hook, rename this file to "prepare-commit-msg".
 
-drawing = False
-mode = True
-ix,iy = -1,-1
+# This hook includes three examples.  The first comments out the
+# "Conflicts:" part of a merge commit.
+#
+# The second includes the output of "git diff --name-status -r"
+# into the message, just before the "git status" output.  It is
+# commented because it doesn't cope with --amend or with squashed
+# commits.
+#
+# The third example adds a Signed-off-by line to the message, that can
+# still be edited.  This is rarely a good idea.
 
-def draw_circle(event,x,y,flags,param):
-    global ix,iy,drawing,mode
-    if event == cv2.EVENT_LBUTTONDOWN:
-        print ('Push')
-        drawing = True
-        ix,iy = x,y
+case "$2,$3" in
+  merge,)
+    /usr/bin/perl -i.bak -ne 's/^/# /, s/^# #/#/ if /^Conflicts/ .. /#/; print' "$1" ;;
 
-    elif event == cv2.EVENT_MOUSEMOVE:
-        if drawing == True:
-            print ('Drawing...')
-            if mode == True:
-                pass
-            else:
-                cv2.circle(img,(x,y),5,(0,0,255),-1)
-        else:
-            pass
-    elif event == cv2.EVENT_LBUTTONUP:
-        print ('Up')
-        drawing = False
-        if mode == True:
-            cv2.rectangle(img,(ix,iy),(x,y),(0,255,0),2)
-        else:
-            cv2.circle(img,(x,y),5,(0,0,255),-1)
+# ,|template,)
+#   /usr/bin/perl -i.bak -pe '
+#      print "\n" . `git diff --cached --name-status -r`
+#	 if /^#/ && $first++ == 0' "$1" ;;
 
-if '__main__' == __name__ :
-    img = np.zeros((512,512,3), np.uint8)
-    cv2.namedWindow('image')
-    cv2.setMouseCallback('image',draw_circle)
-    
-    while(1):
-        cv2.imshow('image',img)
-        k = cv2.waitKey(1) & 0xFF
-        if k == ord('m'):
-            mode = not mode
-        elif k == 27:
-            break
+  *) ;;
+esac
 
-    cv2.destroyAllWindows()
+# SOB=$(git var GIT_AUTHOR_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
+# grep -qs "^$SOB" "$1" || echo "$SOB" >> "$1"
