It's all about the journey, not the outcome. -- Carl Lewis

diff --git a/f132df5765304a18bb8bd3ce8f320a9f b/f132df5765304a18bb8bd3ce8f320a9f
--- a/f132df5765304a18bb8bd3ce8f320a9f
+++ b/f132df5765304a18bb8bd3ce8f320a9f
@@ -1,190 +1,170 @@
-2020年  4月  3日 金曜日 11:21:20 JST
-#include <math.h>
-#include "pg_util.h"
+2020年  4月 20日 月曜日 11:48:09 JST
+#!/bin/sh
+#
+# Copyright (c) 2006, 2008 Junio C Hamano
+#
+# The "pre-rebase" hook is run just before "git rebase" starts doing
+# its job, and can prevent the command from running by exiting with
+# non-zero status.
+#
+# The hook is called with the following parameters:
+#
+# $1 -- the upstream the series was forked from.
+# $2 -- the branch being rebased (or empty when rebasing the current branch).
+#
+# This sample shows how to prevent topic branches that are already
+# merged to 'next' branch from getting rebased, because allowing it
+# would result in rebasing already published history.
 
-// Funtion Prototyping
-void            pg_fix_sub_32(int x, int y, int *z);
-void            pg_fix_sub_32(int x, int y, int *z);
-void            pg_fix_sub_32(int x, int y, int *z);
-void            pg_conv_ftol_fix32_log17_man8(int x, int *z);
-void            pg_conv_ftol_fix32_log17_man8(int x, int *z);
-void            pg_conv_ftol_fix32_log17_man8(int x, int *z);
-void            pg_log_shift_log17_1(int x, int *z);
-void            pg_log_shift_log17_1(int x, int *z);
-void            pg_log_shift_log17_1(int x, int *z);
-void            pg_log_unsigned_add_itp_log17_man8_cut6(LONG x, LONG y,
-							LONG * z);
-void            pg_log_unsigned_add_itp_log17_man8_cut6(LONG x, LONG y,
-							LONG * z);
-void            pg_log_unsigned_add_itp_log17_man8_cut6(LONG x, LONG y,
-							LONG * z);
-void            pg_log_shift_log17_m1(int x, int *z);
-void            pg_log_mul_17(int x, int y, int *z);
-void            pg_log_div_17(int x, int y, int *z);
-void            pg_log_mul_17(int x, int y, int *z);
-void            pg_log_mul_17(int x, int y, int *z);
-void            pg_log_mul_17(int x, int y, int *z);
-void            pg_log_sdiv_17(int x, int y, int *z);
-void            pg_log_sdiv_17(int x, int y, int *z);
-void            pg_log_sdiv_17(int x, int y, int *z);
-void            pg_conv_ltof_log17_man8_fix57(int x, int *z);
-void            pg_conv_ltof_log17_man8_fix57(int x, int *z);
-void            pg_conv_ltof_log17_man8_fix57(int x, int *z);
-void            pg_fix_accum_f57_s64(long long int x, long long int *z);
-void            pg_fix_accum_f57_s64(long long int x, long long int *z);
-void            pg_fix_accum_f57_s64(long long int x, long long int *z);
+publish=next
+basebranch="$1"
+if test "$#" = 2
+then
+	topic="refs/heads/$2"
+else
+	topic=`git symbolic-ref HEAD` ||
+	exit 0 ;# we do not interrupt rebasing detached HEAD
+fi
 
+case "$topic" in
+refs/heads/??/*)
+	;;
+*)
+	exit 0 ;# we do not interrupt others.
+	;;
+esac
 
-#define NJMAX 16384
-static LONG _a[NJMAX][3];
-static unsigned int _xi[NJMAX][3];
-void dump_foset(int n)
-{
-  int i;
-  static int flag=0;
-  static FILE* fp;
+# Now we are dealing with a topic branch being rebased
+# on top of master.  Is it OK to rebase it?
 
-  if(flag==0){
-    fp = fopen("xxx.log","w");
-    flag=1;
-  }
-
-  for(i=0;i<n;i++){
-    fprintf(fp,"%08x,",_xi[i][0]);
-    fprintf(fp,"%08x,",_xi[i][1]);
-    fprintf(fp,"%08x,",_xi[i][2]);
-
-    fprintf(fp,"%016llx,",_a[i][0]);
-    fprintf(fp,"%016llx,",_a[i][1]);
-    fprintf(fp,"%016llx,",_a[i][2]);
-
-    fprintf(fp,"\n");
-  }
-  fflush(fp);
+# Does the topic really exist?
+git show-ref -q "$topic" || {
+	echo >&2 "No such branch $topic"
+	exit 1
 }
 
+# Is topic fully merged to master?
+not_in_master=`git rev-list --pretty=oneline ^master "$topic"`
+if test -z "$not_in_master"
+then
+	echo >&2 "$topic is fully merged to master; better remove it."
+	exit 1 ;# we could allow it, but there is no point.
+fi
+
+# Is topic ever merged to next?  If so you should not be rebasing it.
+only_next_1=`git rev-list ^master "^$topic" ${publish} | sort`
+only_next_2=`git rev-list ^master           ${publish} | sort`
+if test "$only_next_1" = "$only_next_2"
+then
+	not_in_topic=`git rev-list "^$topic" master`
+	if test -z "$not_in_topic"
+	then
+		echo >&2 "$topic is already up-to-date with master"
+		exit 1 ;# we could allow it, but there is no point.
+	else
+		exit 0
+	fi
+else
+	not_in_next=`git rev-list --pretty=oneline ^${publish} "$topic"`
+	/usr/bin/perl -e '
+		my $topic = $ARGV[0];
+		my $msg = "* $topic has commits already merged to public branch:\n";
+		my (%not_in_next) = map {
+			/^([0-9a-f]+) /;
+			($1 => 1);
+		} split(/\n/, $ARGV[1]);
+		for my $elem (map {
+				/^([0-9a-f]+) (.*)$/;
+				[$1 => $2];
+			} split(/\n/, $ARGV[2])) {
+			if (!exists $not_in_next{$elem->[0]}) {
+				if ($msg) {
+					print STDERR $msg;
+					undef $msg;
+				}
+				print STDERR " $elem->[1]\n";
+			}
+		}
+	' "$topic" "$not_in_next" "$not_in_master"
+	exit 1
+fi
+
+exit 0
+
+################################################################
+
+This sample hook safeguards topic branches that have been
+published from being rewound.
+
+The workflow assumed here is:
+
+ * Once a topic branch forks from "master", "master" is never
+   merged into it again (either directly or indirectly).
+
+ * Once a topic branch is fully cooked and merged into "master",
+   it is deleted.  If you need to build on top of it to correct
+   earlier mistakes, a new topic branch is created by forking at
+   the tip of the "master".  This is not strictly necessary, but
+   it makes it easier to keep your history simple.
+
+ * Whenever you need to test or publish your changes to topic
+   branches, merge them into "next" branch.
+
+The script, being an example, hardcodes the publish branch name
+to be "next", but it is trivial to make it configurable via
+$GIT_DIR/config mechanism.
+
+With this workflow, you would want to know:
+
+(1) ... if a topic branch has ever been merged to "next".  Young
+    topic branches can have stupid mistakes you would rather
+    clean up before publishing, and things that have not been
+    merged into other branches can be easily rebased without
+    affecting other people.  But once it is published, you would
+    not want to rewind it.
+
+(2) ... if a topic branch has been fully merged to "master".
+    Then you can delete it.  More importantly, you should not
+    build on top of it -- other people may already want to
+    change things related to the topic as patches against your
+    "master", so if you need further changes, it is better to
+    fork the topic (perhaps with the same name) afresh from the
+    tip of "master".
+
+Let's look at this example:
+
+		   o---o---o---o---o---o---o---o---o---o "next"
+		  /       /           /           /
+		 /   a---a---b A     /           /
+		/   /               /           /
+	       /   /   c---c---c---c B         /
+	      /   /   /             \         /
+	     /   /   /   b---b C     \       /
+	    /   /   /   /             \     /
+    ---o---o---o---o---o---o---o---o---o---o---o "master"
 
 
-// API
-void
-force(double x[][3], double m[], double eps2, double a[][3], int n)
-{
-    double log2(double);
-    int             i, j;
-    long long int   sx_0;
-    long long int   sx_1;
-    long long int   sx_2;
-    int             xi_0;
-    int             xj_0;
-    int             xi_1;
-    int             xj_1;
-    int             xi_2;
-    int             xj_2;
-    int             xij_0;
-    int             xij_1;
-    int             xij_2;
-    LONG            x2_0;
-    LONG            x2_1;
-    LONG            x2_2;
-    LONG            ieps2;
-    LONG            x2y2;
-    LONG            z2e2;
-    int             r2;
-    int             r1;
-    int             mj;
-    int             r3;
-    int             dx_0;
-    int             dx_1;
-    int             mf;
-    int             dx_2;
-    int             fx_0;
-    int             fx_1;
-    int             fx_2;
-    int             f_shift;
-    int             fxs_0;
-    int             fxs_1;
-    int             fxs_2;
-    long long int   ffx_0;
-    long long int   ffx_1;
-    long long int   ffx_2;
+A, B and C are topic branches.
 
-    f_shift = 0x9700;
+ * A has one fix since it was merged up to "next".
 
-    for (i = 0; i < n; i++) {
-      xi_0 = ((unsigned int)((x[i][0] + 50.0)*(42949672.96)+0.5))& 0xFFFFFFFF;
-      xi_1 = ((unsigned int)((x[i][1] + 50.0)*(42949672.96)+0.5))& 0xFFFFFFFF;
-      xi_2 = ((unsigned int)((x[i][2] + 50.0)*(42949672.96)+0.5))& 0xFFFFFFFF;
-      ieps2 = (((int)(256.0*log2(eps2*(1.844674407e+15)))) & 0x7FFF) | 0x8000;
-      _xi[i][0] = xi_0;
-      _xi[i][1] = xi_1;
-      _xi[i][2] = xi_2;
+ * B has finished.  It has been fully merged up to "master" and "next",
+   and is ready to be deleted.
 
-	sx_0 = 0;
-	sx_1 = 0;
-	sx_2 = 0;
+ * C has not merged to "next" at all.
 
-	for (j = n - 1; j >= 0; j--) {
-	  xj_0 = ((unsigned int) ((x[j][0] + 50.0) * 42949672.96 + 0.5)) & 0xFFFFFFFF;
-	  xj_1 = ((unsigned int) ((x[j][1] + 50.0) * 42949672.96 + 0.5)) & 0xFFFFFFFF;
-	  xj_2 = ((unsigned int) ((x[j][2] + 50.0) * 42949672.96 + 0.5)) & 0xFFFFFFFF;
+We would want to allow C to be rebased, refuse A, and encourage
+B to be deleted.
 
-#define MSCALE (4.223095768e+32)
+To compute (1):
 
-	  if (m[j] == 0.0) {
-	    mj = 0;
-	  } else if (m[j] > 0.0) {
-	    mj =(((int)(256.0 * log2(m[j] * MSCALE))) & 0x7FFF) | 0x8000;
-	  } else {
-	    mj =(((int)(256.0 * log2(-m[j] * MSCALE))) & 0x7FFF) | 0x18000;
-	  }
+	git rev-list ^master ^topic next
+	git rev-list ^master        next
 
-	    pg_fix_sub_32(xi_0, xj_0, &xij_0);
-	    pg_fix_sub_32(xi_1, xj_1, &xij_1);
-	    pg_fix_sub_32(xi_2, xj_2, &xij_2);
-	    pg_conv_ftol_fix32_log17_man8(xij_0, &dx_0);
-	    pg_conv_ftol_fix32_log17_man8(xij_1, &dx_1);
-	    pg_conv_ftol_fix32_log17_man8(xij_2, &dx_2);
-	    pg_log_shift_log17_1(dx_0, &x2_0);
-	    pg_log_shift_log17_1(dx_1, &x2_1);
-	    pg_log_shift_log17_1(dx_2, &x2_2);
-	    pg_log_unsigned_add_itp_log17_man8_cut6(x2_0, x2_1, &x2y2);
-	    pg_log_unsigned_add_itp_log17_man8_cut6(x2_2, ieps2, &z2e2);
-	    pg_log_unsigned_add_itp_log17_man8_cut6(x2y2, z2e2, &r2);
-	    pg_log_shift_log17_m1(r2, &r1);
-	    pg_log_mul_17(r2, r1, &r3);
-	    pg_log_div_17(mj, r3, &mf);
-	    pg_log_mul_17(mf, dx_0, &fx_0);
-	    pg_log_mul_17(mf, dx_1, &fx_1);
-	    pg_log_mul_17(mf, dx_2, &fx_2);
-	    pg_log_sdiv_17(fx_0, f_shift, &fxs_0);
-	    pg_log_sdiv_17(fx_1, f_shift, &fxs_1);
-	    pg_log_sdiv_17(fx_2, f_shift, &fxs_2);
-	    pg_conv_ltof_log17_man8_fix57(fxs_0, &ffx_0);
-	    pg_conv_ltof_log17_man8_fix57(fxs_1, &ffx_1);
-	    pg_conv_ltof_log17_man8_fix57(fxs_2, &ffx_2);
-	    pg_fix_accum_f57_s64(ffx_0, &sx_0);
-	    pg_fix_accum_f57_s64(ffx_1, &sx_1);
-	    pg_fix_accum_f57_s64(ffx_2, &sx_2);
-	}
-	_a[i][0] = sx_0;
-	_a[i][1] = sx_1;
-	_a[i][2] = sx_2;
+	if these match, topic has not merged in next at all.
 
-	a[i][0] =
-	    ((double) (sx_0 << 0)) *
-	    ((-(pow(2.0, (double) 32) / (100.0)) *
-	      (pow(2.0, (double) 32) / (100.0)) * 8388608.0 /
-	      (pow(2.0, 95.38) / (1.220703125e-04)))) / pow(2.0, 0.0);
-	a[i][1] =
-	    ((double) (sx_1 << 0)) *
-	    ((-(pow(2.0, (double) 32) / (100.0)) *
-	      (pow(2.0, (double) 32) / (100.0)) * 8388608.0 /
-	      (pow(2.0, 95.38) / (1.220703125e-04)))) / pow(2.0, 0.0);
-	a[i][2] =
-	    ((double) (sx_2 << 0)) *
-	    ((-(pow(2.0, (double) 32) / (100.0)) *
-	      (pow(2.0, (double) 32) / (100.0)) * 8388608.0 /
-	      (pow(2.0, 95.38) / (1.220703125e-04)))) / pow(2.0, 0.0);
-    }
-    dump_foset(n);
-}
+To compute (2):
+
+	git rev-list master..topic
+
+	if this is empty, it is fully merged to "master".
